### ISSUE TITLE
[usability enhancement]  conditional breakpoints

### ISSUE THREAD

**Issue by nww02** [Dotneteer/spectnetide#100]
I don't know if conditional breakpoints work. I tried setting them in the code as (for example)   HL == $80DF  , but that didn't seem to work.   

If conditional breakpoints don't work yet, it would be great to be able to use that VS functionality to help with debugging.     At the moment I have a workaround which looks something like:-

                      LD      A, L
                      CP      $DF
                      JR       Z, SkipIt
                     NOP                           <- breakpoint
        Skipit:   NOP

which  works just fine too, I just have to be careful because it's only comparing the low byte....

**Comment by Dotneteer** [comment]
@nww02, conditional breakpoints do not work yet. Implementing them is already in my backlog (it's a big user story), but I always find something else that is cheaper and more valuable to implement. Hopefully, in a few weeks I can work on this feature.

**Comment by nww02** [comment]
Cool.  :)  thanks :)

**Comment by Dotneteer** [comment]
Released in v1.15.0. 

You can find a detailed description about setting up conditional breakpoints here: https://github.com/Dotneteer/spectnetide/blob/master/Documentation/References/DisassemblyCommands.md#breakpoint-commands.

You can also set up conditional breakpoint for the source code:

When you have just set a breakpoint, select Settings:

![image](https://user-images.githubusercontent.com/4783390/52195430-34d33200-2858-11e9-9293-e97ea8376516.png)

You can define a hit condition:

![image](https://user-images.githubusercontent.com/4783390/52195503-84196280-2858-11e9-92bb-c4175d9974b8.png)

The hit condition expression can be only an integer number.

You can define a filter condition:

![image](https://user-images.githubusercontent.com/4783390/52195617-073ab880-2859-11e9-94d0-b704cacf619e.png)

Though VS allows using a "When changed" clause and not only "Is true" for the Conditional expression, SpectNetIDE supports only "Is true". For the expression you need to use the same syntax as for watch expressions: https://github.com/Dotneteer/spectnetide/blob/master/Documentation/References/WatchCommands.md#understanding-watch-expressions

Enjoy!

**Comment by nww02** [comment]
This is So helpful, thank you! :-)   Debugging loops just got a WHOLE lot easier! thank you so much!! :D
