### ISSUE TITLE
Emulator screen too small

### ISSUE THREAD

**Issue by hadmir** [Dotneteer/spectnetide#102]
It would be nice to have feature to double size of emulator screen Current size is too small on some (large) monitors.

**Comment by Dotneteer** [comment]
@hadmir, would you please help me with a few info how big screen/monitor you have right now? A screenshot would help me :-). 
Right now, the emulator screen size dynamically changes with the wrapping window size, but up to 500% or the original (ZX Spectrum) resolution. I can easily fix it for you.

**Comment by hadmir** [comment]
Currently I have 40" monitor, 4K res, screenshot is here:
![zx](https://user-images.githubusercontent.com/19718133/51526422-98119d00-1e32-11e9-94b0-64eb41fbbaea.png)

**Comment by Dotneteer** [comment]
@hadmir, I see what you mean :-). Nonetheless, as you enlarge the ZX Spectrum Emulator window, the screen size changes dynamically (up to 500%, while it fits in the window). You can also drag the emulator window into a floating window, or even move to the second/third monitor. When I debug a Z80 program, most of the time, I move the emulator to another monitor.
I will change the zoom factor to allow 4K/8K.

**Comment by hadmir** [comment]
OK, I didn't notice this resizing, because it is in "steps", so when I changed size a little bit, it stayed same (small) size. I just needed to resize more and then it works. Thanks!
