### ISSUE TITLE
[feature request]  Define Disassembly ranges in terms of labels

### ISSUE THREAD

**Issue by nww02** [Dotneteer/spectnetide#106]
Rather than type addresses, it would be nice to be able to define the interpretation regions using labels.

i.e. it would be nice to be able to place a label at the start of the app (e.g. zStart) and one at the end (e.g)  zData, and one at the end of the data section (e.g. zEnd).  now,  no matter how much my app changes size, one could reformat easily (without needing to recalculate locations) by doing

md  zStart zData
mb  zData zEnd

I have tried this, but I get a "syntax error" :(

**Comment by Dotneteer** [comment]
Implemented, will be released soon.

**Comment by Dotneteer** [comment]
Released in v1.16.0

**Comment by nww02** [comment]
Brilliant, thanks :)
