### ISSUE TITLE
[feature request] Pragma .repeat

### ISSUE THREAD

**Issue by hadmir** [Dotneteer/spectnetide#108]
Two nice to have pragmas:

a) Repetition
.repeat n
   something
.endrepeat

b) same with possibility to use repetition counter as variable <0, n-1>:
.repeat n a
  something
.endrepeat

Example, create array of byte values 0..255:
.repeat 256 val
    .defb val
.endrepeat

**Comment by Dotneteer** [comment]
@hadmir, I'm happy to tell you that this feature is already implemented. You can find other kinds of loops already offered be the SpectNetIDE assembler here: https://github.com/Dotneteer/spectnetide/blob/master/Documentation/Z80Assembly/Z80AssemblerReference.md#statements :-)

**Comment by hadmir** [comment]
Yeah, I had old version of reference manual, now I see it, there everything and more. ;-) Keep up the good work!
