### ISSUE TITLE
[feature request] Pragma .align

### ISSUE THREAD

**Issue by hadmir** [Dotneteer/spectnetide#109]
pragma .align is basically .skip but for number of bytes defined at compile time.

Example: if I have lookup table of size 30, I can allign it to 32 bytes (.align 32) to ensure that higher byte address is always same, so I can calculate only lower byte. If I need to iterate that array, I can do inc l, instead of inc hl, etc.

**Comment by Dotneteer** [comment]
@hadmir , the SpectNetIDE Assembler already knows `.align`: https://github.com/Dotneteer/spectnetide/blob/master/Documentation/Z80Assembly/Z80AssemblerReference.md#the-align-pragma  :-)

If you've meant something else, please let me know!

**Comment by hadmir** [comment]
Great, documentation you linked is however much better then one I had form "wiki" section of this project (https://github.com/Dotneteer/spectnetide/wiki/Z80-Assembler-Reference).
