### ISSUE TITLE
In Emulator The tool tip shows "Pause" for "Stop" and  "Refresh???" Button

### ISSUE THREAD

**Issue by stuurmn** [Dotneteer/spectnetide#11]
Just a minor one

![2017-11-05 14_15_20-ast3](https://user-images.githubusercontent.com/33286419/32417860-eba5b3aa-c25f-11e7-8ac0-928b5f7091a3.jpg)
![2017-11-05 14_15_28-ast3](https://user-images.githubusercontent.com/33286419/32417861-ebba98b0-c25f-11e7-8c94-3e83c5e7fa87.jpg)

**Comment by Dotneteer** [comment]
Fixed together with issue #9.
