### ISSUE TITLE
[feature request] Pragma .scope/.escope

### ISSUE THREAD

**Issue by zxlame** [Dotneteer/spectnetide#110]
Named scopes like the module from sjasmplus
      .scope Module1
label1
      .escope
     .scope Module2
label1
      .escope
Generate labels Module1_label1 and Module2_label1
Or something like this.

**Comment by Dotneteer** [comment]
@zxlame, the SpectNetIDE assembler knows this feature with a bit different syntax (`.proc` ... `.endp`): https://github.com/Dotneteer/spectnetide/blob/master/Documentation/Z80Assembly/Z80AssemblerReference.md#the-procendp-block

**Comment by zxlame** [comment]
Of course, I read about the proc, but I did not find how to refer to the inner label from the outside.

**Comment by Dotneteer** [comment]
@zxlame, now I see, what you're request is about. It seems a useful feature, so I will think about it! Hopefully, in a few weeks I can implement it -- probably with a bit different syntax that is closer to the approach SpectNetIDE uses right now.

**Comment by Dotneteer** [comment]
@zxlame, To implement this feature (similarly as __sjasm__ does), I need to refactor the Z80 assembler. I use this refactoring to add other cheap features, too, as you can check #114 to #119 (and others, as they will come). :-)

**Comment by Dotneteer** [comment]
Released in v1.17.0
