### ISSUE TITLE
[feature request] #IFUSED

### ISSUE THREAD

**Issue by zxlame** [Dotneteer/spectnetide#112]
And the last thing that I personally lack in the spectnetide. A conditional combination if previously there was a reference to the label. Convenient to create include libraries with selective compilation.

**Comment by Dotneteer** [comment]
@zxlame, I suppose, you'd like to have this feature as SjAsm defines it. Well, SpectNetIDE is a one-pass fixup-type assembler, implementing #IFUSED and #NIFUSED is a hard nut. I see this feature has relatively low value against the investment it needs, so I put it down in my backlog.
_I intend to implement it, but deal with more valuable features first._

**Comment by Dotneteer** [comment]
Implemented, released in 1.18.1.
See more details here: https://dotneteer.github.io/spectnetide/documents/statements#the-ifusedifnused-statements
