### ISSUE TITLE
Z80 Disassembly window:  Change of Display not working?

### ISSUE THREAD

**Issue by stuurmn** [Dotneteer/spectnetide#12]
Hi Istvan,

I don't know if I understand the working correctly but maybe you can have a look?

![2017-11-05 15_57_13-ast4](https://user-images.githubusercontent.com/33286419/32417942-1dab6df8-c261-11e7-9dcb-6fe7134d1a69.jpg)

When I enter MW 3D00 3FFF. The layout stays as above.

I did manage to get it to get the view below earlier on

![2017-11-05 15_49_16-](https://user-images.githubusercontent.com/33286419/32417914-aa6d37f4-c260-11e7-8ec1-dc4e51dc92f7.jpg)

But I'm not sure how I did it.
restarting the program closing opening the disassembly window etc.
I cannot reproduce it.

Also I didn't manage to get the Disassambly View.  (It could be me though...)
Can you have a look?
BR,
Albert

**Comment by Dotneteer** [comment]
A managed to reproduce the issue. This is in close relation with issue #8. This is a result refactoring the virtual machines internal states. I plan not only fix the issue, but add a couple of regression tests.
