### ISSUE TITLE
[feature request] Allow export to Intel HEX file

### ISSUE THREAD

**Issue by gusmanb** [Dotneteer/spectnetide#120]
Hi. I'm writting some code which will be run from an external ROM and to burn it to the ROM I need the .hex file in intel format or similar. Would be great to have the option on the "export" menu to allow the use of the compiler for external hardware.

**Comment by Dotneteer** [comment]
@gusmanb, please provide me a reference for intel .hex format &mdash; one that you find accurate and detailed enough. I'm happy to implement this feature.

**Comment by gusmanb** [comment]
Hi. I always preferred the explanation on the ARM Keil site: http://www.keil.com/support/docs/1584/

Only thing to note, is that record type 05 is not standard, just ignore it and implement the 00 to 04 record types.

Also, this little extension may be of help in the development of this feature: https://marketplace.visualstudio.com/items?itemName=keroc.hex-fmt

Cheers.

**Comment by Dotneteer** [comment]
@gusmanb, thanks for the help!

**Comment by Dotneteer** [comment]
@gusmanb, I have some questions just to be sure that I understood your intention correctly.

So, right now the Export Z80 Program dialog provides many options:

![export_to_hex](https://user-images.githubusercontent.com/4783390/53033384-39f7ca00-3471-11e9-8e3d-9756d5e40791.png)

I guess, you would like to have a third tape file format, namely HEX (or Intel HEX). With this format, you only need a file name, all other options are unnecessary, as this format cannot be loaded in the ZX Spectrum virtual machine.

As I went through the HEX format definition, I had the feeling that right now, while exporting up to 64K (available via 16-bit address), we need only record types __00__ (data record) and __01__ (end-of-file record). Of course, when the compiler will support more pages and banks &mdash; that it does not today, we may need record types __02__ and __04__.

Did I miss something? If you have any ideas or recommendations, please, let me know!

**Comment by gusmanb** [comment]
Hi. Yes, you got everything right :)

This option is useful for three things:

1-Create a custom ROM for the speccy.

As you would be able to create a program at 0x0000 and export it in a
format that will be understandable by eprom/prom/rom/flash burners it
allows you to create a custom rom. As this rom will be of a maximum of 16Kb
this will work without the 02 and 04 record types.

2-Create the "firmware" for an external device (my case)

It's not 100% a firmware  but an 'on the fly' rom mapping, it's a common
technique to map some unused ROM areas to your own code like the Microdrive
did, in my case I want to go beyond, when the user presses a button of my
device it will completely disable the ROM and raise a NMI, in this way I
can take the control of all the hardware and execute my program preserving
everything: stack, registers and RAM. Again, as this will be restricted to
16Kb no need for 02 and 04 records.

3-Create a game cartridge.

Lately on the speccy scene there have been some games released directly as
cartridges, today's FLASH prices make cheaper a cartridge than a real tape,
so having the possibility to load the program into a FLASH is desirable.
This is the only case were the 02 and 04 records would be necessary, and
only in the case of a 128Kb program.


One thing that will be necessary to allow flexibility is to support an
offset for the exported code. I mean, per example, I make a program that
has .ORG #8000 but I want to burn it as a cartridge, the code must continue
"thinking" it's allocated at 0x8000 but the hex file should start at
0x0000, in this way the program will be burnt on the rom/flash /whatever
start and the cartridge will be responsible to remap the flash addresses to
the real ones. Not sure if I have clarified this, I'm sick and my mind is
not very clear  I will try to make tomorrow a better explanation with some
images with the mapping, it will be a lot clearer.

Cheers.

**Comment by gusmanb** [comment]
Here is an image explaining the usage of the offset.
![imagen](https://user-images.githubusercontent.com/4086913/53117862-24a39e00-354c-11e9-8109-30c11ea89f28.png)

**Comment by Dotneteer** [comment]
@gusmanb, Here I send you a private build (v1.17.1) that implements the Intel HEX export. This is a beta, you can test it.

I added a new pragma, `.hdisp` to set up the _Intel HEX displacement_ for your code. So, provided your code start at adress #C300, but you want it to be exported for an external ROM with #0000 start, you should write this:

```
    .org #C300
    .hdisp -#C300
``` 
Should you had any issue, please zip the project and upload so that I can reproduce the problem. Any recommendations are welcome!

[Spect.Net.VsPackage.zip](https://github.com/Dotneteer/spectnetide/files/2887952/Spect.Net.VsPackage.zip)

**Comment by gusmanb** [comment]
Hi.

I've been testing the export, it seems to work ok but I think that some minor changes would make it better.

First, when I thought about the export I thought about a single offset for all the file but as I have verified an offset must be added each time a .org is in the code or it will be exported on the .org address. This is ok, in fact it's better as in this way a more complex address virtualization can be done, but in this case instead of an offset I think it will be better an absolute address like .org does, something like this:

    .org   #8000
    .xorg #0000

        ;
        ;
        ;

    .org   #C000
    .xorg #1000

      ;

What do you think? 

Also, I have been checking the file content, everything looks ok, I have burnt the file to a 24LC512 and dumped it's content and everything seemed to be in place. The only thing I would recommend respect to the file is to create shorter records, usually .hex files use a length of 16 data bytes to make it more readable.

Cheers.

**Comment by Dotneteer** [comment]
@gusman, your feedback seems reasonable :-). I will omit the `.hdisp` pragma, and introduce `.xorg` with the semantics you suggest, and will change the record size to 16 bytes. I'll have a busy weekend, so you can expect me to deliver the modification only the beginning of the next week!

**Comment by Dotneteer** [comment]
@gusman, here is the next private build, according to your suggestions :-)

[Spect.Net.VsPackage.zip](https://github.com/Dotneteer/spectnetide/files/2896545/Spect.Net.VsPackage.zip)

**Comment by gusmanb** [comment]
Hi.

Sorry for the delay, I'm sick and some days mi head doesn't wants to think at all...

I've checked the changes and everything works perfect, now the semantics make sense, the file is perfectly human-readable, the programming software where I test the files "eats" it without any complain and dumping a flashed E2PROM gives a binary with the exact content, I think this can be considered production ready :)

**Comment by Dotneteer** [comment]
Implemented, will be released soon.

**Comment by Dotneteer** [comment]
Released in v1.18.0.
