### ISSUE TITLE
String functions using memory addresses?

### ISSUE THREAD

**Issue by gusmanb** [Dotneteer/spectnetide#121]
To define strings in my program i'm using something like this:

	.ORG #C300

	test_string:
		.defn "Hola pepito!!"
	test_string_2:
		.defn "Una prueba"
	test_string_3:
		.defn "ABCDE?"

The thing is now I don't know how to use string functions like "len" or "lowercase" with this, I've tried "len(test_string)" but it fails. Is it possible to do?

**Comment by Dotneteer** [comment]
@gusmanb, when designing the Z80 Assembler, I was thinking about using labels as addresses for my strings. _The built-in functions run at compile time_, and I did not find a language construct that were convenient during compilation. So, I decided to introduce string constants with `.equ`, and `.var`. This way, you can use strings and string functions, like this:

```
.ORG #C300

test_string:
    .equ "Hola pepito!!"
test_string_2:
    .equ "Una prueba"
test_string_3:
    .equ "ABCDE?"

strings:
    .db length(test_string)
    .defn test_string
    .db length(test_string_2)
    .defn test_string_2
    .db length(test_string_3)
    .defn test_string_3
```

If you can suggest a construct that keeps its compile-time evaluation nature, I'm happy to analyze and implement that!

**Comment by gusmanb** [comment]
Hi.

Ok, I think I understood how to use it.

.ORG #C300

	test_string:
		.equ "Hola pepito!!\0"
	test_string_2:
		.equ "Una prueba\0"
	test_string_3:
		.equ "ABCDE?\0"

	test_string_addr:
		.defn test_string
	test_string_2_addr:
		.defn test_string_2
	test_string_3_addr:
		.defn test_string_3

In this way we can use `test_string` for the string functions and `test_string_addr` for the pointer. Is this the intended way of usage?

**Comment by Dotneteer** [comment]
Yes, absolutely. One little thing: the `.defn` pragma automatically adds a `\0` terminator to the string, however, `.defm` does not.

**Comment by gusmanb** [comment]
Hi.

Ok, perfect, I got it.

Thanks a lot for your help :)
