### ISSUE TITLE
Visual studio 2019 exception

### ISSUE THREAD

**Issue by polevi** [Dotneteer/spectnetide#145]
Typing .defb 0b causes Visual Studio 2019 16.1.1 to throw an System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.

[ActivityLog.xml.txt](https://github.com/Dotneteer/spectnetide/files/3232808/ActivityLog.xml.txt)

**Comment by Dotneteer** [comment]
@polevi, thanks for reporting this bug, I reproduced it both with VS 2019 and VS 2017. I will release a patch soon.

**Comment by Dotneteer** [comment]
Fixed and released (v1.19.1)
