### ISSUE TITLE
ZX Basic

### ISSUE THREAD

**Issue by Ultrahead** [Dotneteer/spectnetide#146]
Hi, does Spectnetide support Boriel's ZX Basic? (http://boriel.com/wiki/en/index.php/ZXBasic/)

**Comment by Dotneteer** [comment]
Hi, @Ultrahead, SpectNetIDE does not support Boriel's ZX Basic.

**Comment by Ultrahead** [comment]
Hi, thanks for replying. Any plans to support it?

Also, I have installed the addon in the latest versión of VS 2019 and when the latter starts it says that the addon was not properly started.

________________________________
De: Istvan Novak <notifications@github.com>
Enviado: Sunday, June 9, 2019 2:08:36 AM
Para: Dotneteer/spectnetide
Cc: Pedro Güida; Mention
Asunto: Re: [Dotneteer/spectnetide] ZX Basic (#146)


Hi, @Ultrahead<https://github.com/Ultrahead>, SpectNetIDE does not support Boriel's ZX Basic.

**Comment by Dotneteer** [comment]
Hi, Pedro, 

I have not planned to support Boriel's Basic. If I have enough request from the community, perhaps I will think about it :-). 

You can find a file named `ActivityLog.xml` file within your user folder, under `AppData\Roaming\Microsoft\VisualStudio\16.0_*` (where `*` is a hexadecimal string). Next time you experience the issue with VS 2019, send me `ActivityLog.xml` (you can contact me directly at dotneteer@hotmail.com).
Now I close this issue, but I will open a new one according to what I see in the log file you send me.

**Comment by Ultrahead** [comment]
Message sent to your email with the log file (entitled "Regarding issue 146"). Please let me know whether you received it.

Hope you think about implementing it since it is a very popular solution with advance features and unfortunately the available plugins are for Visual Studio Code and only support highlighting.

**Comment by Dotneteer** [comment]
Hi Pedro,

Someone had already reported this issue just a few days before you sent me the ActivityLog.xml file. I fixed the issue, released the patch (SpectNetIDE v1.19.2), so it is now available in Visual Studio Marketplace. If you're IDE is set for automatic updates, probably SpectNetIDE has already been updated.

I will make some experiments with Boriel's Basic -- as I do not know it --, so that I get enough knowledge to design its implementation in SpectNetIDE.

**Comment by Ultrahead** [comment]
It works now. Thanks.

> I will make some experiments with Boriel's Basic -- as I do not know it --, so that I get enough knowledge to design its implementation in SpectNetIDE.

Great to know!

**Comment by Dotneteer** [comment]
Pedro, If you can help me with anything related to Boriel's Basic, I'd be happy to implement it :-). If you can send me useful links (to my email) to understand why Boriel's Basic is popular, how the community uses it, it would help me a lot!

**Comment by Ultrahead** [comment]
Sure. I will prepare a list of links and send it to you.

Also, I will report later a few issues I'm experiencing (for instance, I can only run the default sample assembly file with discovery projects on 48K). I will try to reinstall the addon and see if that works.

**Comment by Ultrahead** [comment]
Message sent. Please let me know whether you receive it fine. Regards!

**Comment by Dotneteer** [comment]
The first version of ZX BASIC integration now works in v2.0 (not released yet) :-)
- syntax highlighting
- code compilation
- Run program

Source code debugging is not available yet.
