### ISSUE TITLE
Cannot run nor debug code for other architectures than 48k

### ISSUE THREAD

**Issue by Ultrahead** [Dotneteer/spectnetide#148]
SpectNetIde: 1.19.2
Visual Studio: 16.1.3

The addon is only working for any of the 48K projects. It does not work for other target platforms.

After creating discovery solutions and projects for 128, +2 and +3, and attempted to debug or run the sample assembly code that is included by default on new projects, the emulators are initialized but the code produces a black screen for a second and resets to the corresponding menu of the target platform.

Here's an example of a blank screen when running the default sample for 128k:

![image](https://user-images.githubusercontent.com/12087040/59419271-f0751700-8da0-11e9-921f-d5952b1c73e9.png)

And for +3:

![image](https://user-images.githubusercontent.com/12087040/59419468-637e8d80-8da1-11e9-8640-e9d1f8c8e11c.png)
![image](https://user-images.githubusercontent.com/12087040/59419542-7e510200-8da1-11e9-9d6b-6ca630f1ce26.png)

No warnings or errors, just a reset.

**Comment by Dotneteer** [comment]
@Ultrahead, thank you for reporting this bug. I will fix it and release the patch soon.

The reason it produces the phenomenon you describe is that the demo code I deploy with a new ZX Spectrum project works only in ZX Spectrum 48K mode. Even if you use the 128K, or +3E model, you can run the code in 48K mode with the help of the `.model` directive. So, the code I deploy should start like this:

```
; Put your Z80 assembly code into code files
Start:
	.model Spectrum48 ; *** Sets the 48K mode ***
	.org #8000
        ; ...
```

You can find more details about the `.model` pragma here: https://dotneteer.github.io/spectnetide/documents/pragmas#the-model-pragma

**Comment by Dotneteer** [comment]
Fixed. Released in v1.19.3.

**Comment by Ultrahead** [comment]
Hi, good to know. Thanks.

Any chance that when a program that is being debugged ends, when you press the F5 button (or press the debug icon) it runs the same program again in debug mode?

________________________________
De: Istvan Novak <notifications@github.com>
Enviado: Thursday, June 13, 2019 10:13:31 AM
Para: Dotneteer/spectnetide
Cc: Pedro Güida; Mention
Asunto: Re: [Dotneteer/spectnetide] Cannot run nor debug code for other architectures than 48k (#148)


Closed #148<https://github.com/Dotneteer/spectnetide/issues/148>.

**Comment by Dotneteer** [comment]
@Ultrahead, you cannot use F5 key for this purpose, but there's another simple solution:
1. In Solution Explorer, right-click your main code file (for example, Code.z80asm), and invoke the __Set as default code file__ command.
2. You can use the Ctlr+M, R shortcut key combination to start debugging the code from its entry point.

**Comment by Ultrahead** [comment]
Got it. Thanks

On Jun 14, 2019 1:52 AM, Istvan Novak <notifications@github.com> wrote:

@Ultrahead<https://github.com/Ultrahead>, you cannot use F5 key for this purpose, but there's another simple solution:

  1.  In Solution Explorer, right-click your main code file (for example, Code.z80asm), and invoke the Set as default code file command.
  2.  You can use the Ctlr+M, R shortcut key combination to start debugging the code from its entry point.
