### ISSUE TITLE
Allow a special screen rendering mode when debugging is paused.

### ISSUE THREAD

**Issue by Dotneteer** [Dotneteer/spectnetide#150]
Right now, when the emulator is paused in debug mode, not only the CPU, but also the ULA is paused. Thus the screen shows its partially rendered state.

Provide a mode that allows to show what the user would look if only the CPU was paused but the ULA were still running, as it would help debugging.

**Comment by Dotneteer** [comment]
Will be implemented in v2.0

**Comment by Dotneteer** [comment]
Already implemented in v2.0 -- nonetheless, v2.0 has not been released yet...

**Comment by Ultrahead** [comment]
Hi, ETA for v2.0?

**Comment by Dotneteer** [comment]
Hi, Pedro. I've already implemented this feature in v2.0 :-). I plan to release 2.0 in the middle of November.

**Comment by Ultrahead** [comment]
Great!

Any news about Boriels's Basic support?

On Sep 13, 2019 10:10 AM, Istvan Novak <notifications@github.com> wrote:

Hi, Pedro. I've already implemented this feature in v2.0 :-). I plan to release 2.0 in the middle of November.

**Comment by Dotneteer** [comment]
Boriel's Basic support is a part of v2.0. You can use Basic files for developing ZX Spectrum apps just like Z80 Assembly. I'm not sure that I'll be ready with all important aspects of Boriel's Basic support by the middle of November, as I have some serious issues with it. Nonetheless, I designed the project system with it in mind.

**Comment by Ultrahead** [comment]
Good to know. Thanks!

**Comment by Ultrahead** [comment]
Btw, maybe this link helps: 

https://github.com/boriel/zxbasic

**Comment by boriel** [comment]
I'm @boriel. I'll be glad to help in integrating Boriel ZX Basic :)

**Comment by Dotneteer** [comment]
@boriel, having you here is a great news!

My progress with SpectNetIDE v2.0 is faster than I originally planned. Next week I intend to complete source code debugging (Z80 assembly), and from October 14 I will work on ZX Basic. Right now, I plan to integrate ZX Basic so that it will compile the code to Z80 Assembly, and then -- using the existing infrastructure -- from Z80 Assembly to binary code. With this setup I expect that I can leverage on the existing SpectNetIDE source code integrated debugger.

I've already prepared my Z80 Assembly to be compatible with ZX Basic ASM output :-).

If you see any flow in this idea, or have any hint or clue for me, you're welcome !

**Comment by Ultrahead** [comment]
> @boriel, having you here is a great news!

@Dotneteer: you're welcome! ;)

**Comment by Dotneteer** [comment]
@boriel, please contant me at dotneteer@hotmail.com. I have a number of question that I would like to handle with you offsite.
Thanks in advance,
Istvan
