### ISSUE TITLE
Including Binary Files

### ISSUE THREAD

**Issue by Ultrahead** [Dotneteer/spectnetide#151]
Is it possible to include a binary file? For example,

MYSPRITE:
#include "mySprite.bin"

... where the file contains something like this:

![image](https://user-images.githubusercontent.com/12087040/59554923-1f49e380-8f81-11e9-8cc4-0b2268bfa617.png)

... representing a sprite? 

If not, would it be possible to add it? (either with include reserved word or a new one "includebin"?)

**Comment by Dotneteer** [comment]
@Ultrahead,

Yes, it's possible :-) SpectNetIDE support `.includebin`: https://dotneteer.github.io/spectnetide/documents/pragmas#the-includebin-pragma

**Comment by Ultrahead** [comment]
Good to know, thanks!

To end a macro, can you always use .endm? Or are there specific end macro statements for certain macros?

________________________________
De: Istvan Novak <notifications@github.com>
Enviado: Sunday, June 16, 2019 6:46:46 AM
Para: Dotneteer/spectnetide
Cc: Pedro Güida; Mention
Asunto: Re: [Dotneteer/spectnetide] Including Binary Files (#151)


@Ultrahead<https://github.com/Ultrahead>,

Yes, it's possible :-) SpectNetIDE support .includebin: https://dotneteer.github.io/spectnetide/documents/pragmas#the-includebin-pragma

**Comment by Dotneteer** [comment]
@Ultrahead, I guess, you can find answers for most of your questions in regard to SpectNetIDE Z80 assembler in the documentation section, here: https://dotneteer.github.io/spectnetide/documents/main-features.html.

Read not only the Macros section, but the others, and then you will understand the approach the Assember uses.
