### ISSUE TITLE
Wrong code generation for IX, IY bit instructions

### ISSUE THREAD

**Issue by imp5imp5** [Dotneteer/spectnetide#154]
For example: "set 6,(ix+1)" compiled to DD CB **F6 01** instead of DD CB **01 F6**

**Comment by Dotneteer** [comment]
@imp5imp5, thanks for your bug report! I will check this and issue a fix as soon as possible.
Istvan

**Comment by Dotneteer** [comment]
@imp5imp5, the bug fix is ready. Update the SpectNetIde extension (v1.19.5) in Visual Studio  to use it!

Please, do not hesitate, if you find a bug, contact me :-).

If you like this IDE, please star it on GitHub!

**Comment by imp5imp5** [comment]
Thank you!
