### ISSUE TITLE
Incorrect value in port 0x1F (Kempston joystick)

### ISSUE THREAD

**Issue by imp5imp5** [Dotneteer/spectnetide#155]
255 is always read from this port, which corresponds to all simultaneously pressed buttons.
(Expected '0')

**Comment by Dotneteer** [comment]
Hi @imp5imp5, SpectNetIDE does not support Kempston joystick yet. I have this feature in the bottom of my backlog for a long time. Now, I pull it to the top :-), and will implement it soon.

**Comment by Dotneteer** [comment]
@imp5imp5, I've implemented Kempston joystick emulation in v1.20.0. To sign that a Kempston joystick is present, use this option to tunr on/off emulation. When turned off, you can select a combination of ZX Spectrum keys to emulate the direction and fire of Kempston joystick:

![image](https://user-images.githubusercontent.com/4783390/63213677-7732d100-c10f-11e9-961f-52042b74a535.png)

I plan to provide more support, including key mappings in SpectNetIDE v2.0.

I hope, you like this feature :-).

**Comment by imp5imp5** [comment]
Thank you! It works now.
