### ISSUE TITLE
[v2p1] Cannot set .z80asm as default one

### ISSUE THREAD

**Issue by Ultrahead** [Dotneteer/spectnetide#158]
In version 2 preview one, when you handle multiple projects in one solution, once you pick a default .z80asm file, you cannot set the default file with another .z80asm file in a different project.

(btw, congrats for you release)

**Comment by Dotneteer** [comment]
Thanks for reporting, tomorrow I will check it!

**Comment by Ultrahead** [comment]
The problem is that if, for example, you add a +3 project, and then try to run the asm file that comes with it by default, nothing happens beyond loading the initial menu of the OS

**Comment by Dotneteer** [comment]
@Ultrahead, there's three different bug behind the phenomenon you described :-)
1. Setting the active project item has a bug.
2. Selecting the default program item has a bug.
3. Running code on +3E has a bug.
I fill fix all of them soon.

**Comment by Dotneteer** [comment]
@Ultrahead , FYI: the first two bugs are fixed.

**Comment by Dotneteer** [comment]
Fixed. Will be released in v2.0-preview2.

**Comment by Dotneteer** [comment]
Released in v2.0-preview2
