### ISSUE TITLE
[v2p1] Missing Tags When Creating Projects

### ISSUE THREAD

**Issue by Ultrahead** [Dotneteer/spectnetide#159]
In VS 2019 (and I guess in VS 2017, too) you can associate tags to project templates so as to rapidly get to project types for Languages, Platforms and Project Types. For example, C++ Windows Games.

It would be great to have this tags for ZX projects (at least, the Games one). I don't know if you can create new tags or have to use the buil-in ones, but if yo can, you could get creative and have something like ZX Langs, ZX Spectrum, Games.

**Comment by Dotneteer** [comment]
Great suggestion! In a few days, You'll have it :-)

**Comment by Dotneteer** [comment]
I added the following tags: `ZX Spectrum`, `ZX Spectrum Languages`, `Z80 Assembly`, `ZX BASIC`, `Games`. If you have other suggestions, I'm pretty open :-).
I will release these changes in v2.0-preview2.

**Comment by Dotneteer** [comment]
Released in v2.0-preview2
