### ISSUE TITLE
[v2p1] No Boriel ZX Basic Example Integration

### ISSUE THREAD

**Issue by Ultrahead** [Dotneteer/spectnetide#160]
It would be handy if you include in your site an integration sample with Boriel's ZX Basic. So as to catch the attention or both, newcomers and experience devs.

**Comment by Dotneteer** [comment]
You're right, @Ultrahead :-). Originally I planned the first review in Mid-November but eventually released it earlier. If you can share a bit more details with me about what you think, it would be a great help.

This is what I have in the documentation right now:
https://dotneteer.github.io/spectnetide/getting-started/setup-zx-basic
https://dotneteer.github.io/spectnetide/getting-started/use-zx-basic

Thanks in advance,
Istvan

**Comment by Ultrahead** [comment]
Thanks for asking my thoughts. I have read the sections. 

My comments for section 1: "Setup ZX Basic"

1) You are right, many links takes you nowhere but the wiki is now on: https://zxbasic.readthedocs.io/ 
2) Instead of mentioning Win32 it would be better to tell the user that the Win32 files usually follow this naming structure: zxbasic-x.x.x-win32.zip. Also, for those who prefer the global version, should follow the instructions on github to also get phyton. 
3) Once installed, the command cannot be executed in Powershell on Windows.
4) I could not found the ZXBasic options in Visual Studio (inside the SpectNetIDE section). It would be nice to known if there is any additional step to "unlock" it.
5) At the end of the section you could add something like "Great! Now you are ready to proceed to the next section: Use ZX Basic".

Regarding section 2: "Use ZX Basic"

1) The redaction in bullet #1 is odd. When you install a discovery project, does it include a .zxbas by default in the project? 
2) As a result of 4) above, I'm not seeing the ZX Basic Program option in the add new item dialog box.
3) At the end, of the section add something like "You can find more examples in ZX Basic's wiki: http ..."

I would also add a new section 3 Debug ZX Basic with a (Coming Soon)

**Comment by Ultrahead** [comment]
Sorry, I had installed v1.2. You should add in Readme where to find the installer for the v2 preview.

**Comment by Dotneteer** [comment]
@Ultrahead, Thanks for the suggestions, I changed the documentation accordingly.
When you create a new project, it contains a default `.zxbas` file within the `ZxBasicFiles` project.

**Comment by Ultrahead** [comment]
No .zxbas is included by default when a new project is created. No ZxBasicFiles folder is found. Bug?

**Comment by Dotneteer** [comment]
@Ultrahead, if you do not find a `ZxBasicFiles` folder, probably you have both SpectNetIDE v1.0 and v2.0 installed on you computer. SpectNetIDE does not work properly with this configuration :-(. See more info here: https://dotneteer.github.io/spectnetide/getting-started/install-spectnetide-2

This may be the cause of the issue you experience.

**Comment by Ultrahead** [comment]
Checked it. And no, I have only v2 installed. Maybe uninstalling it from within VS left some garbage registers?

**Comment by Dotneteer** [comment]
@Ultrahead, if you can, please send me an email to dotneteer@hotmail.com so that I have your email address. I'd be happy to organize a Skype call with you the see what's going on on your IDE, provided, you are ready to do that.

**Comment by Ultrahead** [comment]
Message sent! (you will find two video recordings showing what I get when I create a project)
