### ISSUE TITLE
[v2p2] Enhancement: watch assembly output of compiled zxbas files

### ISSUE THREAD

**Issue by Ultrahead** [Dotneteer/spectnetide#164]
It would be nice, for .zxbas files, to see the produced assembler compilation when you select the compile file menu option.

The workaround I found for this is to run the project, pause it, and step over code until the compiled assembler file opens.

**Comment by Dotneteer** [comment]
@Ultrahead, great feature suggestion :-)

**Comment by Dotneteer** [comment]
Implemented, will be released in v2.0 preview 3. You can read the details here: https://dotneteer.github.io/spectnetide/getting-started/use-zx-basic#zx-basic-compilation

**Comment by Dotneteer** [comment]
Released in Preview 3.
