### ISSUE TITLE
[v2p2] zxbas files not included in new project

### ISSUE THREAD

**Issue by Ultrahead** [Dotneteer/spectnetide#165]
When you create a new project, the folder containing the .zxbas file and the file it-self are both created but excluded from the solution/project by default,

The workaround is to expose all files in the solution explorer of VS and then manually include them.

**Comment by Dotneteer** [comment]
@Ultrahead, I still not managed to reproduce the issue. Some of my contacts at Microsoft (she works in the Visual Studio team) suggested me an uninstall/reinstall VS 2019 with restarting your Windows after the reinstall and install.

I'm so sorry that I cannot suggest you anything else than this potential workaround :-(

**Comment by Ultrahead** [comment]
No problem.

**Comment by Dotneteer** [comment]
@Ultrahead, a fellow of mine signed a similar issue directly to me. During a skype call, we found a solution &mdash; it may work in your case, too:

- Close all open VS 2019/VS 2017 instances
- Select the `AppData\Local\CustomProjectSystems` folder within your user profile folder. (On my machine it is `C:\Users\dotne\AppData\Local\CustomeProjectSystems`)
- Remove the entire contents of `Spect.Net.CodeDiscover`.
- Open VS 2019 and create a new ZX Spectrum project &mdash; this action reinitializes the contents of the just deleted folder.

I hope, it will help :-)

**Comment by Ultrahead** [comment]
Hi, sorry for the late response. Yes, that was it! Now works ok. Thanks

**Comment by Dotneteer** [comment]
Pedro, I'm happy that finally we managed to solve it :-)

**Comment by Ultrahead** [comment]
Me too!
