### ISSUE TITLE
Unable to create project (preview 2)

### ISSUE THREAD

**Issue by altexa** [Dotneteer/spectnetide#166]
Unable to create project.  Following instructions here;
https://dotneteer.github.io/spectnetide/getting-started/create-zx-spectrum-48k-project-2#article

This is a fresh install of visual studio 2019 community.  I installed the extension according to the instructions here:
https://dotneteer.github.io/spectnetide/getting-started/install-spectnetide-2#article

When I give the project name and click create I get :
![image](https://user-images.githubusercontent.com/34234230/70313234-82705080-1815-11ea-9e69-461d9aec9dc8.png)

**Comment by Dotneteer** [comment]
Hi @altexa, I'm travelling during the next 8 days, I have no opportunity to look into the SpectNetIDE code unless I'm back :-(.

**Comment by altexa** [comment]
No hurry :)  I'll try installing more 'bits' of VS to see if that helps

**Comment by maziac** [comment]
Same problem here. I also installed a fresh copy of VS2019.

**Comment by Dotneteer** [comment]
@altexa, @maziac, I did not manage to reproduce the issue. Nonetheless, I made an experiment.

I removed VS 2019 Community and after restarting my machine, I installed it again with selecting only the **.NET desktop development** only workload. After that, I could set up SpectNetIDE and create a new ZX Spectrum project.

Nonetheless, my standard VS 2019 setup uses two other workloads, **ASP.NET and web development**, and **Visual Studio Extension development**, too -- but as the experience shows, these are not required for running SpectNetIDE.

I used VS 2019 Community v16.4.2

Please check if this info helps.

**Comment by maziac** [comment]
It's working now for me. After installing .NET desktop development the error is gone.
Thanks.

**Comment by Dotneteer** [comment]
Woooh. Thanks, @maziac, I add this learning to the documentation.

**Comment by altexa** [comment]
Confirmed…adding the .NET desktop development bundle fixed the problem.

 

Many thanks!

**Comment by Dotneteer** [comment]
Fixed in Preview 3.
