### ISSUE TITLE
Add Light Color Theme

### ISSUE THREAD

**Issue by deadman2000** [Dotneteer/spectnetide#168]
Current scheme do my eyes hurt

![Screenshot](https://user-images.githubusercontent.com/12889180/72135840-70477c00-3398-11ea-8ece-e1ee6b469494.png)

**Comment by Dotneteer** [comment]
@deadman2000, I do not plan to add a light color theme to SpectNetIDE in the near future. Nonetheless, you can set up your own color scheme through the Options dialog (in Environments | Font and color), as the figure shows:

![devenv_hTrITPFYbg](https://user-images.githubusercontent.com/4783390/72199799-22d31980-3441-11ea-9b5b-674247691f98.png)
