### ISSUE TITLE
vsix does not install in current vscode. Error: "extension/package.json not found inside zip."

### ISSUE THREAD

**Issue by agnunez** [Dotneteer/spectnetide#169]
Following installation tutorial, I tried to install this IDE in current VScode and, it does not appear in extension list, and while trying manual installation of vsix file, it refuse to install with an error

 "extension/package.json not found inside zip."

**Comment by Dotneteer** [comment]
@agnunez, Sorry, but SpectNetIDE works only with Visual Studio 2019, but not with Visual Studio Code :-(

**Comment by pitommasi** [comment]
Is there any plan to make it usable in VSCode?

**Comment by Dotneteer** [comment]
@pitommasi, I have good news for you :-). There are not only plans for VS Code, but I've already started a project: https://github.com/Dotneteer/kliveide

**Comment by pitommasi** [comment]
...and it's installed, thanks a lot!!

**Comment by Dotneteer** [comment]
Of course, you can :-). Be aware of that this stuff is an early alpha. The VS Code Extension does not work without the Klive Emulator.

**Comment by pitommasi** [comment]
Good, thanks for the heads up!
