### ISSUE TITLE
[Low Priority tweaks]  Keyboard tweaks 

### ISSUE THREAD

**Issue by nww02** [Dotneteer/spectnetide#176]
Just a few niceties for keyboard usage, I was wondering if you had time, please could you consider the below....  these are _NOT_ bugs, just some feedback. Please close and delete at your convenience :)

* Are "SHIFT" and "ALT-GR" transposed?  When I'm typing in "L" mode, I've noticed that to get an extended character I press "SHIFT", but to get a capital letter I press "ALT-GR" (or "ALT").   Might it be more expected for Shift to be CAPS SHIFT, and maybe ALT to be SymShift?

* On the on-screen spectrum keyboard, I can't seem to make CAPS SHIFT and SYM SHIFT "sticky".  They click but they don't do anything.  I guess they don't have to, really haha.  It's useful for figuring the key combo to get something, though..  I guess syou could click on the SHIFT key and for them to be 'sticky' until another key is clicked?

* Is it possible to allow the on-screen keyboard to resize?  I know it's probably a lot of work, but it takes up a lot of screen on my laptop :)    

* If you click RIGHT on the edge of the Graphics icon on the number keys, you often get BOTH the graphic character AND the number character printed one after the other, like it's detected the hit twice.

**Comment by Dotneteer** [comment]
@nww02 , thanks for the suggestion. Here are my responses:
* *Point 1*: **I will add an option that allows you to swap SHIFT and ALT-GR.** As about two years ago, I released SpectNetIDE in the way it is, this is the less painful solution I can imagine. So, you'll be able to use the combination you like.
* *Point 2*: Though the keys are not sticky, they still have use: you can click on them and use them as the physical keybord. Of course, these actions have no real use when typing a BASIC program, can can be used when programs (games) run.
* *Point 3*: You can resize the Spectrum keyboard to fit to the tool window in Tool | Options | Spect.Net IDE:

![devenv_DRfpvyQb9i](https://user-images.githubusercontent.com/4783390/76876033-a231fe80-6871-11ea-9d8c-df52ff6d4a37.png)

* *Point 4*: I did not manage to reproduce this issue in my computer, though I'm sure it happens on yours. Try both available layouts, probably the Spectrum 128K layout fits better to your needs:

![devenv_yMpJdAnbPG](https://user-images.githubusercontent.com/4783390/76876727-a4e12380-6872-11ea-86a5-7b7741dce730.png)

**Comment by nww02** [comment]
Ah! OK, I didn't find the Options for Spect.Net!  On my laptop the window isn't tall enough, and it's off the bottom of the Option panel!  Thanks, will check it out :) :)

**Comment by Dotneteer** [comment]
SHIFT/ALT/GR Swapping option in implemented, will be released in Preview 6

**Comment by nww02** [comment]
You are a scholar and a gentleman! :)    Love it!  I think it'll make the emulator much easier to start with for newcomers if the keys are in this configuration!  Thanks :) :)

**Comment by Dotneteer** [comment]
Point 1 implemented, will be released in Preview 6. More info: https://dotneteer.github.io/spectnetide/documents/pragmas#the-injectopt-pragma

**Comment by nww02** [comment]
That's cool, thanks!  I'll add the pragma to my code while I'm debugging.. It's useful to be able to run chunks of code modularly to check cause-and-effect bugs.   I think I'll find the template and add it into the default Code.z80asm template, it's very useful.

I think that link is for Issue #175 though.
https://github.com/Dotneteer/spectnetide/issues/175

**Comment by Dotneteer** [comment]
Yes, you're rightt, it's for #175.

**Comment by Dotneteer** [comment]
Released in v2 Preview 6.
