### ISSUE TITLE
Error loading virtual machine state

### ISSUE THREAD

**Issue by nww02** [Dotneteer/spectnetide#177]
If I attempt to start debugging of my code with ^M^R or ^M R, I get an error "Error loading virtual machine state".   (see below)
I also got the same error the first time I tried to start the emulator.  
Version: 2.0.6

---------------------------
Microsoft Visual Studio
---------------------------
Error loading virtual machine state

Cannot find type 'Spect.Net.SpectrumEmu.Cpu.Z80Cpu+Z80DeviceState, Spect.Net.SpectrumEmu, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' to deserialize CPU state information
---------------------------
OK   
---------------------------

**Comment by Dotneteer** [comment]
@nww02, Recently, I have made small fixes in the vmstate format that may cause this issue. Please, follow these steps, I guess it may solve the issue.

1. Close VS 2019 (all open instances)
2. Under your solution folder, you find a `.SpectNetIde` folder. Remove it.
3. Start VS 2019, open the solution and try now.

If these steps do not work, please, zip the entire solution folder and attach it to a comment, or email it directly to me: dotneteer@hotmail.com.

**Comment by nww02** [comment]
I'll give it a try! Thanks :)

**Comment by Dotneteer** [comment]
@nww02, Did it worked, or the issue still exists?

**Comment by nww02** [comment]
I just had it happen this morning, so gave it a try, and YES, it SORT of worked.....   Some interestingly mixed results, which I'll raise in a separate bug :)     

The only new thing I noticed was that THIS time I got the following error (with a typo in 'length').
`
No code to run.

The lenght of the compiled code is 0, so there is no code to inject into the virtual machine and run.
`
