### ISSUE TITLE
[ANNOYANCE only]  VS19 hangs for 10+ seconds when doing file actions in a solution

### ISSUE THREAD

**Issue by nww02** [Dotneteer/spectnetide#178]
Doing any file operations in a SpectNetIDE project (like add new file, delete file or rename file) causes VS to hang and white-screen for between 10 seconds and a minute.

Not had this with C# projects.. Any idea why it might be doing that?!

version 2.0.6

**Comment by nww02** [comment]
The problem seems to get exponentially more acute with each new file or folder.  I tried to add a folder about 2 minutes ago, and it hung for over two minutes.  Devenv.exe was slowly consuming more and more RAM.  It didn't release it after it came back from the white-screen-of-pause.

**Comment by Dotneteer** [comment]
I managed to reproduce this issue. I guess it appeared after one of the last VS updates (as similar surprising issues pretty often happen with VS updates). Nonetheless, I investigate the issue and fix it asap. Please, send me the VS 2019 version number you use (you can find it in the Help | About dialog).

**Comment by nww02** [comment]
I am using VS 2019   
Version 16.4.6
.Net Framework 4.8.03761

I'm up to about 6 files and I can make a cup of tea while it adds a new code file XD haha,.

**Comment by Dotneteer** [comment]
I was testing this issue and observed that the delay is somewhere within VS 2019. I was helpless, but the new VS 2019 16.5.0 seems to solve this issue. After upgrade, I do not have this issue. (Well, I have several other problems with 16.5.0, so I need to adjust my code :-(, but at least this one seems to go away). Can you check if it works on your computer, too?

**Comment by nww02** [comment]
OOF, a 1.6Gig download!  That'll take me a while to download... I'll let you know :)

**Comment by nww02** [comment]
Yes. the update has shortened the time considerably!  I haven't had this problem with C#, so I wonder what M$ broke in 16.4 :)

Closing now :)  Thanks again.
