### ISSUE TITLE
[FEATURE REQUEST]  Import Binary File

### ISSUE THREAD

**Issue by nww02** [Dotneteer/spectnetide#179]
To help content importing, like graphics, fonts, sounds etc, might it be possible to add a feature to SpectNetIDE....  An import option to the Solution Explorer's Context Menu?

"Import Binary File".

This would ask for a file (OpenFileDialog)... Select <FILENAME.EXT>, then would create a new file at the point in the solution file tree where the import was initiated called <FILENAME.EXT.Z80ASM>  which contains a defb conversion of the binary file prefixed with a label  FILENAME_EXT:

e.g.  if I imported a file called "sprite.ch8", which contained:

00 00 00 00 00 00 00 00  18 18 18 18 18 00 18 00
6C 6C 24 00 00 00 00 00  00 34 7E 34 2C 7E 2C 00
10 7C 60 7C 04 7C 10 00  E2 E4 E8 10 2E 4E 8E 00
3C 24 3C 30 6A 64 7E 00  18 18 08 00 00 00 00 00

The output would be a file   "sprite.ch8.z80asm" which contained something like::

// Insert copyright information here
// Imported from SPRITE.CH8  17/3/2020 14:36:00

sprite_ch8:  defb 0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00 ,0x18,0x18,0x18,0x18,0x18,0x00,0x18,0x00, 0x6C,0x6C,0x24,0x00,0x00,0x00,0x00,0x00, 0x00,0x34,0x7E,0x34,0x2C,0x7E,0x2C,0x00, 0x10,0x7C,0x60,0x7C,0x04,0x7C,0x10,0x00, 0xE2,0xE4,0xE8,0x10,0x2E,0x4E,0x8E,0x00, 0x3C,0x24,0x3C,0x30,0x6A,0x64,0x7E,0x00, 0x18,0x18,0x08,0x00,0x00,0x00,0x00,0x00

ALTERNATIVELY, if this is too complex / contradicts the design ethos of SpectNet, perhaps a pragma, so that the user can just specify it like this:

sprite_ch8:
.IMPORTBINARY  <sprite.ch8>

Which injects the defb at compile time?

Many thanks in advance :)

**Comment by Dotneteer** [comment]
@nww02, I do not know, if you have already read about this SpectNetIDE assembler pragma, probably it fist for you: https://dotneteer.github.io/spectnetide/documents/pragmas#the-includebin-pragma  :-)

**Comment by nww02** [comment]
Oh, I'm so sorry.. *slaps head* ... I've been using the Wiki : https://github.com/Dotneteer/spectnetide/wiki/Z80-Assembler-Reference   as my reference, and I didn't see that pragma!  That's perfect, I'll use that! :D
