### ISSUE TITLE
[FEATURE/INTENDED?] Debugging and running uses the current edited (or selected) file as the starting point?

### ISSUE THREAD

**Issue by nww02** [Dotneteer/spectnetide#180]
(Apologies, this one is hard to explain, cos it's a UX / familiarity thing)

I have a program in a few files:-

A main file  (code.z80asm)
   A common definitions file (common.z80asm)
   Some library function files.  (e.g. fonts.z80asm)

My main code looks like this

```
.org 8000
<some Assembly>
#include "common.z80asm"
#include "fonts.z80asm"

```

When I compile the solution by right-clicking on the project in the Solution Explorer, or the code.z80asm file, the compilation works perfectly.

BUT: When I attempt to debug by right-clicking on a different file (e.g. fonts) or using the ^M^R hotkey combination while editing the fonts.z80asm (which depends on common.z80asm) I get dependency errors, as if "Debug Program" is only attempting to compile and run THAT FILE, and not the whole program.

If this is intended, may I recommend changing the text in the context menu to be "Compile FILE" or "Debug FILE" etc, but leave the context menu options on the project as "Compile PROGRAM", so that it's clear that the two have different effect?

However, with ^M^R & ^MR, as this feature is ONLY available by right-clicking on the project (as "Run  Program"/"Debug Program" (not on "Debug File"), no matter where I am editing, I would expect it to attempt to compile the whole project rather than work at the file-level...  It just means that I cannot make an edit and quickly debug, I have to sort through the files, locate the code.z80asm and do it from there each time (cf. pressing F5 in C# where you can do it from any file).

SECONDLY....
  I don't #include "common.zx80asm" in the fonts file.  Should I be?   The compiler does not complain of duplicated labels if I don't put #ifndef guards within common.z80asm even when it's being (theoretically) included multiple times....  In C++-land this would throw me "blahblah already defined" errors :)

**Comment by Dotneteer** [comment]
After reading several times, I hope, I understood what you meant :-). Let me think about a descent solution...
According to SECONDLY, I do not know whether it is a feature or a bug... Could you zip and upload your entire sample project with all the files so that I can look into it and check it?

**Comment by nww02** [comment]
I have uploaded a video to demonstrate the different ways to compile / run..

https://youtu.be/QaTvpky7LMM

**Comment by Dotneteer** [comment]
@nww02, I managed to find and fix the bug. Here I send you a private build for testing.
[Spect.Net.VsPackage.zip](https://github.com/Dotneteer/spectnetide/files/4431486/Spect.Net.VsPackage.zip)

Back to youe "Secondly" topic: the compiler should complain for duplicate identyifiers. So, if you include "common.z80asm" twice, the compiler should raise an error. If not, that must be a bug. Should you find such a project, please, zip the entire solution folder and send me for investigation.

**Comment by nww02** [comment]
I have done some experimentation.    When I changed some ordering of the #includes in the MAIN code file it did start throwing errors, albeit not consistently.

I think if I have a MAIN code file, a COMMON file and a LIBRARY file (which uses things in the COMMON file), then if I do this in my CODE file:-

```
.org 8000
#include COMMON
#include LIBRARY
start:
    >> code goes here <<
```

...it works, because the compiler works a little differently to C++ which would attempt to iron out the symbol dependencies in the LIBRARY.cpp files using the LIBRARY.h dependency hierarchy before gluing them into the MAIN hierarchy.. 

In Spectnet, there's no .h files, so when the pieces get put together, the LIBRARY file does not need to reference the COMMON file at all because COMMON is already included in the temporary file being built.  

However, if I attempt to compile the LIBRARY on its own, it breaks because the COMMON file is not imported....


I've just put guard #IFNDEFs around my common.z80asm and#included it from ALL my library files now, just as I do in C++... That works nicely.  I was just confused why I was able to compile the code (as written above) without them.... Having read and re-read your dox I think I understand now :)

**Comment by Dotneteer** [comment]
Released in v2 Preview 6.

**Comment by nww02** [comment]
:)  Thanks
