### ISSUE TITLE
[BUG / DEVELOPER ERROR?]  ^M^R and Inject/RANDOMIZE produce different results

### ISSUE THREAD

**Issue by nww02** [Dotneteer/spectnetide#181]
Version: 2.0.6
Description: Different results between automatically running and manually with inject

I've uploaded a video to demonstrate:   [ -> Youtube](https://youtu.be/W5CCzAg0YNs)

First:       Run by inject / RANDOMIZE USR   - Works Perfectly - prints a UDG at top left

Second:   Run by ^M^R with .ent  set to $ -  Doesn't Work spectacularly! :laughing: 

third:       ~~Run~~ ~~by~~ ~~^M^R~~ ~~with~~ ~~.ent~~ ~~set~~ ~~to~~  ~~8000~~ <IGNORE THIS ONE, I forgot to add "$">

I have uploaded my project [-> Dropbox](https://www.dropbox.com/s/zcr5ozklrazmcm1/SpectrumCodeDiscovery4.7z?dl=0)  If this isn't just me being silly, and you want to investigate..

Cheers!

Nick

**Comment by Dotneteer** [comment]
This is not a bug, it is a feature :-)
When you use the Run program command for the injected code, it *jumps* to the start address of the code. If you use RANDOMIZE USR _address_, it *calls* the code. The issue with you code is, that it ends with a RET. Of course, it works with RANDOMIZE USR, but will return to a junk address when starting it with Run program. Here is a little help that you can use to create code that can be used with both ways: https://dotneteer.github.io/spectnetide/documents/pragmas#the-xent-pragma

**Comment by nww02** [comment]
Ahhh.. Superb! Thank you :) :)    I hadn't spotted that, and I'd scoured the .ent documentation for clues, but didn't see .xent! :) Thank you!!!!!!!!!!!!!!!!!!!!!

**Comment by nww02** [comment]
By the way, I tried to use the code you linked to, but I get two errors:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Z0407: The XENT pragma can be used only in the global scope.	SpectrumCodeDiscovery4	D:\Development\Speccy\Projects\SpectrumCodeDiscovery4\SpectrumCodeDiscovery4\Z80CodeFiles\Code.z80asm	22	
Error		Z0407: The ENT pragma can be used only in the global scope.	SpectrumCodeDiscovery4	D:\Development\Speccy\Projects\SpectrumCodeDiscovery4\SpectrumCodeDiscovery4\Z80CodeFiles\Code.z80asm	3	
```

My code is:


```
.model Spectrum48
#define FASTSCREEN

Start:
.org 8000h
.ent 8000h
			call	Main
			jp		Start



#include "common.z80asm"
#include "graphics.z80asm"
#include "string_output.z80asm"



str_loc:	  defw 0x0a0a
str_to_pr: defn "String to print"


Main:
	.xent $
	print_string(0x0505,str_to_pr,ink(1) | paper(2))
ret


```

**Comment by Dotneteer** [comment]
Thanks for signing this BUG :-). I managed to reproduce it. Here is a private hotfix for you (please, rename it to .vsix):

[Spect.Net.VsPackage.zip](https://github.com/Dotneteer/spectnetide/files/4416541/Spect.Net.VsPackage.zip)

**Comment by nww02** [comment]
:) Thanks!   

I've never been able to get the jp #12ac to work at the end of the code.. I always end up with a black screen of death, hence the infinite loop.
