### ISSUE TITLE
ZX Emulator settings?

### ISSUE THREAD

**Issue by Angel996** [Dotneteer/spectnetide#190]
Hello.

On my Windows 10 system there is a problem with sound playback. I wrote a simple "beep" routine in assembly which plays fine on other emulators. On Spectnetide sound is garbled, plays differently on every run, sometimes sound chunk replays in a couple of seconds by itself. It's obviously a problem with sound playback/buffer in Windows. Is it possible to change playback device/driver/buffer size (Wave/DirectX) for the ZX emulator? I looked thru the docs and found no link to emulator settings. Also other settings, control setup, kempston etc? Is it possible?

p.s. Thanks for your great work, it's amazing.

**Comment by Dotneteer** [comment]
@Angel996, I know about the sound issues :-(. It's the result of the "co-operation" of Windows and Visual Studio. Rewriting the sound system is in my backlog, in the weeks ahead I will start working on it.
In the Tools|Options dialog, in the Spect.NET IDE tab, you find a lot of settings including the keyboard, joystick, compiler, emulator, etc. Unfortunately, no settings for sound (yet).

**Comment by Angel996** [comment]
My suggestion is then to add information on Tools|Options emulator settings to the page 

https://dotneteer.github.io/spectnetide/getting-started/zx-spectrum-emulator-window

It is not mentioned there. It's important, especially for newbies like me.
