### ISSUE TITLE
Non-existant Z80 instructions

### ISSUE THREAD

**Issue by Angel996** [Dotneteer/spectnetide#192]
By chance discovered, that two non-existent Z80 instructions are actually being assembled, and given some random opcodes.

```
.model Spectrum48
.org #8000
jr p,$+4
jr m,$+6
```

Assembly result is:

`50 02 58 04`

Instead, error msg should be thrown.

**Comment by Dotneteer** [comment]
Thanks for signing it, @Angel996!

**Comment by Dotneteer** [comment]
Fixed, will be released in Preview 7.

**Comment by Dotneteer** [comment]
Released in Preview 8.
