### ISSUE TITLE
Exporting? does it work? :)

### ISSUE THREAD

**Issue by Angel996** [Dotneteer/spectnetide#197]
Hello.

I can't seem to be able to export anything from there. Right click .z80asm file, _Export program_  just yields nothing. Even specifying a non-existant directory (like c:/Temp/ which is set by default) returns "The code has been exported". The reason I need to export is because sound playback isn't correct, so I would like to hear it in an external emulator.

Does it work at all? :)

**Comment by Angel996** [comment]
UPDATE: There seems to be some permissions issue. I changed the export filename to _./code.tzx_, now it was able to export correctly and I can also see the _Code.tap_ file in the _TapeFiles_ folder. The file is also in the .SpecNetIde/Exports directory. If export path is set to _C:/Temp/Code.tap_, even if _C:/Temp_ does exist, export just does nothing.

**Comment by Dotneteer** [comment]
@Angel996 , I check this issue soon!

**Comment by Dotneteer** [comment]
@Angel996, I reproduced and fixed the issue you reported. Thanks for finding it! Here is the private build that contains the fix:

[Spect.Net.VsPackage.zip](https://github.com/Dotneteer/spectnetide/files/4656971/Spect.Net.VsPackage.zip)

I plan to release it in Preview 9.

**Comment by Dotneteer** [comment]
Released in v2 Preview 9.
