### ISSUE TITLE
Floating bus implementation

### ISSUE THREAD

**Issue by Angel996** [Dotneteer/spectnetide#198]
Hello again. :)

There are several implementations of floating bus phenomenon, as described here:

http://sky.relative-path.com/zx/floating_bus.html

Although I have _.model Spectrum48_ specified at start of my code, in terms of floating bus the emulator acts as if it were a +2A, not the 48k model. Syncing only works if inputting from port #FD instead of port #FF. Please check out the two versions of floating bus code (48k and +2A/+3) at the link above to reproduce behavior.

The standalone _SpecIde_ emulator, however, works as intended in both _issue2_ and _plus2a_ modes.

**Comment by Dotneteer** [comment]
Thanks, @Angel996. I do not promise I will be fast :-). First I need to check the article you sent me.

**Comment by Dotneteer** [comment]
@Angel996, here is a fix for the floating bus issue. Thes samples in the article above now work with this release:

[Spect.Net.VsPackage.zip](https://github.com/Dotneteer/spectnetide/files/4661336/Spect.Net.VsPackage.zip)

**Comment by Dotneteer** [comment]
Released in v2 Preview 9.
