### ISSUE TITLE
[Feature] Support for ZX Spectrum Next

### ISSUE THREAD

**Issue by Ultrahead** [Dotneteer/spectnetide#201]
This is an issue opened to follow up progress regarding dev tools and emulator support for the ZX Spectrum Next. So that updates can be posted here.

Is this still a planned feature for SpectNetIDE v2.x?

**Comment by Dotneteer** [comment]
Yes, @Ultrahead, it is :-). Nonetheless, I need the help of the community to implement it. The documentation of ZX Spectrum Next still lacks important details.

**Comment by Ultrahead** [comment]
I see. I will try to call for help.In the meantine, you could check ZEsarUX code for the Next:https://github.com/chernandezba/zesarux/blob/master/src/tbblue.hhttps://github.com/chernandezba/zesarux/blob/master/src/tbblue.hIt may give you an idea of the undocumented parts. Comments are in Spanish but Google translator would give you a fair translation.

**Comment by boriel** [comment]
CSpect is the "official" ZX Next emulator (C# - Mono, even run in Linux). ZX Basic, on the other side, already supports Next ASM when using `--zxnext` command line flag.

**Comment by em00k** [comment]
Which bits are considered lacking in details? Please let you now so this can be fixed. The WIKI is here [[](https://wiki.specnext.dev/Main_Page)] ZEsarUX does not yet support the full Next, however CSpect is more complete, and offiers a plugin system to allow fine grain control.

**Comment by Dotneteer** [comment]
Guys, thank you very much for your help :-). What I need to support ZX Spectrum Next is the help of the community to reveal and discuss unknown, undocumented, or ambiguous things.

I appreciate the work Cesar has been doing with ZEsarUX, and also Mike's work with CSpect. As Cesar has open-sourced his project, it is much easier to use as a source for learning. As a C# guy, I'm not as happy with CSpect's closeness, nonetheless, I can accept that Mike has a reason behind this decision.

David, I know the ZX Spectrum Next Wiki, this is the first source of my knowledge. I find it a decent set of documents, which is crucial for developers creating programs for the ZX Spectrum Next. However, this documentation is probably not enough for emulator implementers. I also accept that it does not have to be written with them in mind.

By the time I started to work on SpectNetIDE, the first ZX Spectrum Next Kickstarter campaign was over its backing period. Hopefully, the second is coming soon :-).

By turning to the community, I'd like to spare time to spend just for hunting docs and information. So this is the first challenge where I expect help:

**TBBlue/ZX Spectrum Next is sophisticated hardware compared to ZX Spectrum  48/128/2/2+/3+. For me, it is not clear what kind of hardware components are together when you start a TBBlue machine with ZX Spectrum with its minimal/default configuration. (ROMS, RAM, Z80 CPU, etc.). I want to learn it to have a better understanding of what hardware/software components I need to emulate to start a working Next.**

**Comment by Ultrahead** [comment]
@em00k , @boriel : do you guys know anyone that can provide the info @Dotneteer needs?

**Comment by em00k** [comment]
There is a discord channel where these in-depth questions can be asked. https://discord.gg/J3pyXk

**Comment by Dotneteer** [comment]
Closing this issue now, as it's obsolete.
