### ISSUE TITLE
"The operation could not be completed. Interface is not supported"

### ISSUE THREAD

**Issue by albertom65** [Dotneteer/spectnetide#203]
I installed VS2017 from scratch (but I have also VS2015 installed).
I installed your IDE.
I created a new 48K project.
It works, I can run it, change the code etc. But then when I save the whole project I receive the error "The operation could not be completed. Interface is not supported".

The root directory of the project is created (eg. Spectrum48TestProject) but not the subfolders.

The solution I found is to go to tools/option, Project and solutions/General and check the Save new projects when created.

**Comment by Dotneteer** [comment]
@albertom65, thanks reporting this issue, and investigating the solution with the Project and solutions option :-). I will check this issue soon to find what may be the root cause behind it.

**Comment by Dotneteer** [comment]
@albertom65, I did not manage to reproduce the issue :-(. Even if the **Project and solutions|General|Save new projects** option was turned off, I did not receive the issue. I used VS 2017 version 15.9.27.
