### ISSUE TITLE
"Rainbow" sample program runs incorrectly in the emulator

### ISSUE THREAD

**Issue by ezolotko** [Dotneteer/spectnetide#211]
Hi,
Here is what I get when I run the sample Rainbow program from [here](https://dotneteer.github.io/spectnetide/getting-started/create-a-z80-program#article):
![image](https://user-images.githubusercontent.com/993271/101290759-f3718c00-380c-11eb-859a-9cf47d90252b.png)
However this program works fine on the real Spectrum (no broken lines).
I am using the latest version of the VS extension on VS2019.

**Comment by TheStruggleForAntiSpaghetti** [comment]
You did create a 48k and not a 128k project, did you?

**Comment by ezolotko** [comment]
Yes, it is a 48k project. And as the tutorial says:
> Select the first Spectrum 48K model (PAL - Normal Speed) from the list, and click Create.

**Comment by TheStruggleForAntiSpaghetti** [comment]
Ok, just wanted to make sure as the 128k has different timing.

**Comment by Dotneteer** [comment]
@ezolotko, sorry for ignoring your bug report so long. Unfortunately, I cannot reproduce the issue. Here is a screenshot I have just been created with the rainbow program:

![devenv_ilHUJs6vfb](https://user-images.githubusercontent.com/4783390/102346969-02d89e00-3fa0-11eb-9089-cb5bd15ab881.png)

It shows that the program works as expected.
