### ISSUE TITLE
Another compiling hello world error: Unexpected token: 'core'

### ISSUE THREAD

**Issue by bwganblack** [Dotneteer/spectnetide#227]
Attempting to run Program.zxbas produces a .z80asm file but then results in this error message:

![image](https://user-images.githubusercontent.com/14203581/136557943-a01cf424-b348-4c0e-be84-0013947a7977.png)

The error list yields this:

![image](https://user-images.githubusercontent.com/14203581/136558352-844ad6aa-78b8-4883-85d8-71480da8c71e.png)

Each error appears to refer to `push namespace core`, for example here on line 68:

![image](https://user-images.githubusercontent.com/14203581/136559320-9eb2c9c9-9c3e-4b9c-92f4-4147a92d0301.png)

I'm using SpecNetIDE v2 (Preview 10) provided here https://github.com/Dotneteer/spectnetide/issues/205#issuecomment-745254804 and ZXBasic 1.15.2.

Is there a solution without rolling back the version of ZXBasic? Thanks.

**Comment by gusmanb** [comment]
You need to update to the V2.0.11, it includes support for namespaces in ZXBasic

https://github.com/Dotneteer/spectnetide/releases

**Comment by bwganblack** [comment]
Thanks that works! Installing through Manage Extensions in Visual Studio 2019, only 2.0.9 is available at present.
