### ISSUE TITLE
In debug mode F11 makes code window active but code window doesn't listen to F11 (highlites not always working)

### ISSUE THREAD

**Issue by stuurmn** [Dotneteer/spectnetide#23]
When I dubug a program and press F11 the z80code window becomes active and sometimes highlites the line with the current instruction (But not always)

The F11 key works fine from the emulator window and from the dissassembly window. But because it jumps to Z80code window, F11 doesn't react and the program doesn't continue for 1 step.

![2017-11-09 09_57_31-spectrumcodediscovery1 - microsoft visual studio - experimental instance](https://user-images.githubusercontent.com/33286419/32596697-74827236-c534-11e7-8cca-0228ef898e78.jpg)
Here the Emulator windows is active When Pressing F11
Z80 dissasembly is updated and the z80code is updated. But it looses focus from the emulator window. ( Or maybe that is not the problem and the  solution would be to have the z80code window listen to keypresses?)

![2017-11-09 10_01_14-spectrumcodediscovery1 - microsoft visual studio - experimental instance](https://user-images.githubusercontent.com/33286419/32596838-fadca40a-c534-11e7-87f4-753f37337150.jpg)
Now the Z80code windows is active

![2017-11-09 09_37_36-spectrumcodediscovery1 - microsoft visual studio - experimental instance](https://user-images.githubusercontent.com/33286419/32596527-e3992742-c533-11e7-997c-35153ed6ebc9.jpg)
Pressing F11 This current line was highlited

![2017-11-09 09_38_22-spectrumcodediscovery1 - microsoft visual studio - experimental instance](https://user-images.githubusercontent.com/33286419/32596492-c108fa68-c533-11e7-80f4-2c8f5b4c9c6e.jpg)

Pressing F11 Here the current instruction is not highlited

![2017-11-09 09_37_59-spectrumcodediscovery1 - microsoft visual studio - experimental instance](https://user-images.githubusercontent.com/33286419/32596498-c647400c-c533-11e7-9724-3529107a4324.jpg)

Pressing F11 Same here the current instruction is not highlited (Although the z80code seems to scroll to the correct place...)

**Comment by Dotneteer** [comment]
This is a reproducable, but unfortunately non-deterministic bug. As my explorations -- so far -- point out, this must be a race-condition-related issue within the `Z80DebugTaggerProvider` class.

**Comment by stuurmn** [comment]
Interesting!
Never heard of Race-condition ( I had to look it up, wiki gave a good explanation)


Is the z80 code window of a different type then the dissasembly and the emulator windows?
When the z80code window is not docked it shows up as a 2nd VS session  (I mean the 2 green squares)




![2017-11-09 16_59_00-](https://user-images.githubusercontent.com/33286419/32615620-7cab31d2-c570-11e7-8d3c-c0de0a4b7000.jpg)


Also I noticed that the disassembly register, emulator window alsways stays on top of the IDE, while the z80 code window can hide underneath any program

**Comment by Dotneteer** [comment]
That would be a long story, if I wanted to tell it to you all :-). Briefly, the z80 code window is a *document window*, while the others are *tool windows*, by Visual Studio Extensibility terms. This is why they behave differently. Document windows are displayed in the task bar separately, if the are in floating mode.

**Comment by stuurmn** [comment]
I see,
I thought maybe because of the different type of window the communication from the emulator / disassembly window was not fully supported/or just different.

Would it be possible to copy the content of the z80code windows in a tool window?  Would that make a difference?
(On the other hand, we allready have the disassembly window which works very well (just not the full label but the generated label).

Maybe best to leave it for now?

**Comment by Dotneteer** [comment]
I try to redesign the code part that is responsible for highlighting the current breakpoint.
