### ISSUE TITLE
SpectNetIDE menu not appearing with VS2019

### ISSUE THREAD

**Issue by Smashcat** [Dotneteer/spectnetide#238]
Installed the extension and restarted VS. I could create a new SPectNetIDE project, and it created the default project, however no top level menu added to IDE, and no way to assemble or test in any way. Checking the project properties results in an empty window with "No properties" in it. I tried uninstalling and reinstalling both versions of SpectNetIDE and neither currently work with VS2019.

Is this project abandoned, is there a replacement?

**Comment by gusmanb** [comment]
There is no top level menu, the menu is inside the "Extensions" one. I think you have checked the V1 documentation, check the V2.

https://dotneteer.github.io/spectnetide/getting-started/create-zx-spectrum-48k-project-2#article

**Comment by Smashcat** [comment]
Thanks, I did have the V1 IDE on there but it was not working at all. No top menu or extension menu. So I uninstalled it again and installed V2 and it now works. Thanks for the help.
