### ISSUE TITLE
VS hangs completely in debugging mode

### ISSUE THREAD

**Issue by stuurmn** [Dotneteer/spectnetide#24]
I can't always reproduce this one.

But it looks when I'm in debugging mode and the dissassembly and the registers and the memory window are open and I  click on F5 "Start debugging" VS hangs.
Some times I can continue after a while. Often I have to break off (throught the task manager)

The emulator is running but I think slowly

I would say the more of the tool windows are open the more likely it is that VS hangs
(Just by switching between Pause and F5  (I haven't got any breakpoints in the line of running code)

If I put a breakpoint where it comes all the time ( And I only use F5) then I can have multiple of those tool windows open.

**Comment by Dotneteer** [comment]
I did manage to reproduce this issue. It seems the issue is within the ZX Spectrum Memory tool window.
