### ISSUE TITLE
Z80 instruction only recognised in lower case

### ISSUE THREAD

**Issue by stuurmn** [Dotneteer/spectnetide#28]
DJNZ is not recognised as a valid.
djnz is been seen as a valid opcode

![2017-11-12 22_37_37-freewayfrog - microsoft visual studio - experimental instance](https://user-images.githubusercontent.com/33286419/32703725-58ebdc92-c7fa-11e7-931e-8634e9b9c3c3.jpg)

**Comment by Dotneteer** [comment]
I will check all other Z80 instructions for similar issues.
