### ISSUE TITLE
When the debugger is paused at a HALT instruction, neither step-into nor step-over cannot continue with the subsequent instruction following HALT.

### ISSUE THREAD

**Issue by Dotneteer** [Dotneteer/spectnetide#46]

**Comment by Dotneteer** [comment]
Closed by mistake...

**Comment by stuurmn** [comment]
Seems to have re appeared? (48k)
In the emulator the program is running fine.
In the disassembly window and the code window the cursor is stuck at the halt statement.
Also in the toolwindow the PC is stuck at the same address as the halt statement
