### ISSUE TITLE
Undocumented Z80  

### ISSUE THREAD

**Issue by stuurmn** [Dotneteer/spectnetide#55]
In the Jet Set Willy Source code

They are using the instructions:
![image](https://user-images.githubusercontent.com/33286419/34074006-cb4c3a2c-e2a6-11e7-9b0b-839c717e2d59.png)

![image](https://user-images.githubusercontent.com/33286419/34074066-d1d15dcc-e2a7-11e7-9c79-26fd7d43318a.png)

IXH and IXL are not recognised.

Is it possible you can add them?

Thanks,
Albert

**Comment by Dotneteer** [comment]
Albert, there are two notations for the low and high bytes of IX/IY registers:

 1. XL, XH, YL, YH
 2. IXL, IXH, IYL, IYH

Right now, the Z80 assembler supports only notation #1. Soon I will implement #2, as an alternative notation.
