### ISSUE TITLE
Dissassembly window doesnt show the current code (When loaded from tape)

### ISSUE THREAD

**Issue by stuurmn** [Dotneteer/spectnetide#56]
When Tape loaded and I go to debug:  (Spectrum 48k mode)

![2017-12-17 21_52_24-jetsetwillytape](https://user-images.githubusercontent.com/33286419/34083740-b0b105b0-e375-11e7-99aa-389fd7a2f915.jpg)
The disassembly window is showing the wrong contents

![2017-12-17 21_53_00-jetsetwillytape](https://user-images.githubusercontent.com/33286419/34083747-c3be0acc-e375-11e7-86be-d0167765729e.jpg)

When Explicitely telling in the disassembly window to view it as disassembled code it is up to date
The memory windows seems to be up to date

![2017-12-17 21_53_37-](https://user-images.githubusercontent.com/33286419/34083767-02a5fe16-e376-11e7-92aa-17c84f4c2d92.jpg)

**Comment by Dotneteer** [comment]
Besides fixing this issue, I will also add an "RD" (Re-disassembly) command to the Disassembly tool window command prompt so that any time the developer wants he or she could refresh the disassembly view.
