### ISSUE TITLE
Request: Set breakpoint in Disassembley window

### ISSUE THREAD

**Issue by stuurmn** [Dotneteer/spectnetide#57]
2)	Set breakpoints from the disassembly window

 
Would it be possible to set breakpoints in this window?

![spectnetidedebug](https://user-images.githubusercontent.com/33286419/34227283-eb3cb2ac-e5cc-11e7-9e2d-445ec796e33b.jpg)

Reason:
While debugging from a tape file there is no source file to place breakpoints. You can start debugging when the program is running. But you have to do this step by step. Can take a while before you have reached the point you want to see
It would be nice if you can set a breakpoint from the disassembly window so you can go straight to the interesting part.

**Comment by Dotneteer** [comment]
You can add breakpoint to the machine code in the Disassembly window with the following commands:
SB _hhhh_: Set breakpoint for address _hhhh_
TB _hhhh_: Toggles breakpoint for _hhhh_
RB _hhhh_ : Removes breakpoint from _hhhh_
EB: Erase all breakpoints

I hope it helps. May I close this issue with this answer?

**Comment by stuurmn** [comment]
Sorry,
It is even in the instructions which I asked you to make a direct link to by pressing on the `>`
Maybe at some stage we can think of an even more obvious way to draw the atention to the help file (a big flashing `?` , or a police siren followed by a background voice saying  For help press the ` >`.    :-)

Yes you can close it

**Comment by Dotneteer** [comment]
:-)
