### ISSUE TITLE
Request:  1)	Send code to emulator without executing 

### ISSUE THREAD

**Issue by stuurmn** [Dotneteer/spectnetide#58]
Request extra option: Send to emulator without executing the code

 
![spectnetidecode to spectrum](https://user-images.githubusercontent.com/33286419/34227392-3bce1c06-e5cd-11e7-918c-0eec4fa3dba0.jpg)

Is it possible to send the code directly to the emulator without executing the code
So you can execute it with RANDOMIZE USR command in Basic?

I was looking at a piece of code that does a RET and then crashes. I think it tries to get back to basic. But because it is not called from basic. It hasn’t got not anywhere to return to.  (That’s why I had the idea)

**Comment by stuurmn** [comment]
Any change that you can also add around the same place the option for doing a "Check Syntax " only without running the code? 
Because I do not alway want to execute the code, but I do like to see if I'm not making too many error

**Comment by Dotneteer** [comment]
I implemented the commands you requested :-). You can find them in the project context menu (uses the default code file), and in each code file menu:

- __Compile Z80 code__: Compiles the code without running it. If there are errors, those are displayed in the Error List window. On successful compilation you get a confirmation message. The confirmation can be disabled in the Tools|Options|SpectNet IDE page ("Confirm successful code compilation")
- __Inject Z80 code__: Compiles the code, restarts the virtual machine, but does not execute the code.

**Comment by stuurmn** [comment]
Thank you very much,
This weekend I'l have a look!
