### ISSUE TITLE
Request: Make it possible to have a directive without instructions but with only a comment

### ISSUE THREAD

**Issue by stuurmn** [Dotneteer/spectnetide#59]
(Very low priority)
I came across this construction.

![2017-12-22 22_19_57-demo_libzx - microsoft visual studio - experimental instance](https://user-images.githubusercontent.com/33286419/34312726-7478ba08-e766-11e7-883e-ab03c0be9286.jpg)

But as you can see the comment is white and not recognised as a comment it first likes to see an instruction. (off cause the comment could be on the next line ant then it works without problems)

**Comment by Dotneteer** [comment]
According to the screenshot, I assume you wanted ta ask a label-only line with comment :-)

**Comment by stuurmn** [comment]
Yes, you are right! (I need to work on my terminlogy)

Thats why I like to include screenshots: 
A picture says more than a thousand words.  :-)

Thanks for the quick change.

**Comment by Dotneteer** [comment]
I should have designed the assembler to accept it right from the beginning :-).
