### ISSUE TITLE
SpectNetIde VM hangs it self and complete restart from experimental Instance necassary

### ISSUE THREAD

**Issue by stuurmn** [Dotneteer/spectnetide#62]
Hi Istvan,

You may remember that a while a go I noticed that I sometimes had to restart SpectNetIde experimental instance because when I started a program I couldn't start another program anymore. And I couldn't reproduce this behaviour consitently.

I think I found the way to reproduce it.

1) Start SpectNetIde and load project --> Run Z80 program leave it running.
2) Open other project. ( No need to execute a file)
3) Open the same project from step 1 and try to Run the z80 program. The program doesn't restart (Or try to run another z80 program. and it doesn't strat the new program)

After exiting SpectNetIde and restarting the experimental environment everything is back to normal.

BR,
Albert

**Comment by Dotneteer** [comment]
Thanks for the reproduction steps, I will check soon :-)

**Comment by Dotneteer** [comment]
Managed to reproduce the bug. Fix is on the way.

**Comment by Dotneteer** [comment]
The issue was that the VM did not refreshed the screen, though it was running.

**Comment by stuurmn** [comment]
Excellent!
Thanks for fixing it!
