### ISSUE TITLE
Defs should report an error for an undefined symbol

### ISSUE THREAD

**Issue by davidblackuk** [Dotneteer/spectnetide#63]
Hi

This took a while to track down. I miss typed a constant and the following compiles

a_label: defs not_defined_symbol

even though the symbol is not defined (seem to emit defs 0 which even in itself might be an error)

As part of tracking this down i added code to dump the symbol table to the output window. A tool window to show the symbols would be great.

D

**Comment by Dotneteer** [comment]
David, thanks for the report. I will fix this bug soon.

**Comment by Dotneteer** [comment]
David, your report was very useful :-). I have found the same issues with the FILLB and FILLW pragmas, too. Now, all these issues are fixed.
I opened a new issue, #64 where you can add comments about how you would implement displaying the compilation symbols. Should this tool window display the output of the latest compilation? Please, share your ideas with me!
