### ISSUE TITLE
Create a tool window to lists Z80 Assembler symbols after compilation.

### ISSUE THREAD

**Issue by Dotneteer** [Dotneteer/spectnetide#64]
(_Request by David Black_) It would be useful to display compilation symbols to help troubleshooting with errors due to undefined symbols. The way how this should be implemented is not clear at the moment, I need to investigate it.

**Comment by davidblackuk** [comment]
Hi Istvan

The request wasn't just related to undefined symbols, but more broad. In the SpecNet IDE (which has become awesome) i'm developing a game. Recently i'm trying to debug an issue where my sprite buffers are not being initialized correctly. By adding some code to dump the symbols i could see the following (very much truncated)

SPRT_0 - 9e57
SPRT_BG_OFFSET - 16
SPRT_BUFF_LEN - 34
STACK_POINTER_COPY - a096
START - 8000
START_GAME - 8266

so now i can go to the zx spectrum memory window and enter "g 9e57" to examine the start of my dynamically generated sprite buffers. these symbol values also allowed me to determine the issues i mentioned about undefined values.

So a window that post-assembly listed all symbol names and values would be awesome in memory and debug modes.

Also the ability to enter 'g SPRT_0' into the memory window would also be fantastic.

However seeing the memory layout is very powerful on its own. Back in the early '80s when i was using assemblers on the spectrum the last symbol output was $ (which you support). My current project is no where near using the full 32K available, but when I start getting close I need to know how much memory i'm using. 

Hope this helps i'll add more if required.

**Comment by Dotneteer** [comment]
Working on it...

**Comment by Dotneteer** [comment]
David, the first version of __Z80 Assembler Output__ tool window (You find it in the ZX Spectrum IDE) provides the info you need. After you compile/run the code, this window displays the output details, such as a summary, symbols, and fixups.
Fixups are those symbols and expressions that cannot be promptly evaluated in the first pass of the assembler. If those symbols cannot be resolved in the second pass, they remain "unresolved" and can be seen in the Fixups view (use the __Show unresolved fixups__ button to display only them ).

**Comment by davidblackuk** [comment]
Hi István

Appreciate your efforts. The ide is really looking good. I’m trying to start back blogging again and wrote this

http://www.overtakenbyevents.com/Spectrum-development-then-and-now-part2/

Hope you like it. 

D

**Comment by Dotneteer** [comment]
David, this article is fantastic! Thank you for supporting SpectNetIde! I'd be happy to involve you more deeply in the project -- I have so many plans and ideas, but me alone is not enough to implement everything...
