### ISSUE TITLE
Crash when editing a new file

### ISSUE THREAD

**Issue by davidblackuk** [Dotneteer/spectnetide#66]
Hi istvan

I found a reproducible crash in the IDE, thought you'd be interested.

Steps to reproduce

Add a new z80Asm file through visual studio
go to the end of the org #8000 line
press return, then tab
start typing defb

Result
A crash of visual studio on the press of the letter b

Hope this helps

**Comment by davidblackuk** [comment]
Follow up. I think the problem is way more wide spread. I got latest version this morning an I am having crashes in many places, for instance typing .equ crashes the IDE too.

**Comment by Dotneteer** [comment]
Thanks for your feedback. I managed to find the issue, it was caused by a simple change in the Z80 Assembly parser I introduced to support the Z80 Assembler Output tool window.
