### ISSUE TITLE
Crash on start up when running from source

### ISSUE THREAD

**Issue by davidblackuk** [Dotneteer/spectnetide#67]
Hi Istvan

I got latest version and after I launch SpectNetIde and opening my solution, I get an error dialog saying

An exception was encountered this may be caused by an extension.

At this point i cannot open any files. I have attached the log file they recommended looking at. I also emptied my appdata\local\Temp folder to see if it was a stale MEF cache (no luck)

[ActivityLog.txt](https://github.com/Dotneteer/spectnetide/files/1778421/ActivityLog.txt)

**Comment by davidblackuk** [comment]
I al;so see this in the output window for SpectNet

System.Runtime.InteropServices.InvalidComObjectException: COM object that has been separated from its underlying RCW cannot be used.
   at System.StubHelpers.StubHelpers.StubRegisterRCW(Object pThis)
   at Windows.Foundation.Diagnostics.IAsyncCausalityTracerStatics.TraceOperationCompletion(CausalityTraceLevel traceLevel, CausalitySource source, Guid platformId, UInt64 operationId, AsyncCausalityStatus status)
   at System.Threading.Tasks.AsyncCausalityTracer.TraceOperationCompletion(CausalityTraceLevel traceLevel, Int32 taskId, AsyncCausalityStatus status)The program '[13548] devenv.exe' has exited with code 0 (0x0).

**Comment by Dotneteer** [comment]
(David, please try the newest version from master. As I see, you are 35 commits behind the current master.)
  
My guess is that the VS Extension cache got polluted. This is how you can clean it:

You can find your local extension folder in `%LocalAppData%\Microsoft\VisualStudio\15.0_something\Extensions`

Mine is in `C:\Users\dotne\AppData\Local\Microsoft\VisualStudio\15.0_acd5c2a1Exp\Extensions.`

Clear all file and folders under Extensions (while no VS instances run). The next time you start Visual Studio and run the code in the Experimental instance, most of the issues you’ve sent me must be gone.

Should the problem still exist, please send me (email) the solution that cauese the issue. Of course, I will treat it with discrecy.

**Comment by davidblackuk** [comment]
Updated and cleared the cache and it's working now thanks.
