### ISSUE TITLE
Ability to debug without reset?

### ISSUE THREAD

**Issue by rockdemon** [Dotneteer/spectnetide#68]
Hi,

I love the work you've done here. Something that would improve usability for me would be either a way to take a snapshot of a last known good state and the ablity to code into that snapshot or maybe the ability to be able to just compile into a running instance?

My use case when i was playing with it last night was to write a little basic program to call some machine code in a loop or similar. If i want to add or change the machine code routine i have to re-create the basic program, and it would be handy to have an easy way around this.

Thanks for your efforts! Looking forward to the next version greatly!

Rich

**Comment by Dotneteer** [comment]
Rich,

When you run the Spectrum virtual machine, you can pause it, and save its state into a .vmstate file. Later, you can reload the state and continue running the machine. You can find these commands on the toolbar of the ZX Spectrum Emulator tool window. (Please note, the Add vm State to Project command has not been implemented yet.)

Nonentheless, it's a good idea to provide a way to inject the code into the machine without reseting it. 

So my suggestion is the following:
* I modify the existing __Inject Z80 Program__ command. If the machine does not run, it starts it &mdash; just like the current command does.
* If the machine runs, the command provides a popup that tells you to pause the machine.
* If the machine is paused, the command injects the code &mdash; and keeps the machine paused.

What do you think about it?

**Comment by rockdemon** [comment]
THat sounds fantastic and thanks for the tips too :)
