### ISSUE TITLE
Wrong keys being returned while running from emulator

### ISSUE THREAD

**Issue by stuurmn** [Dotneteer/spectnetide#7]
Hi,

I was experimenting with a Z80 tutorial and I noticed the following

When I run the code --> Context menu --> Run Z80 program the key presses were not recognised correctly.  instead of recognising the values 111, 112, 114  it saw the results as F4h F5h F7h.   the spacebar was recognised as correctly with 32

But when I exported the program to a tap file and run it directly in the emulator it was working fine. there the values 111, 112 etc were read correctly

The code checks for 
; invite player input
		ld hl, last_k			; LAST K system variable
		ld a, (hl)				; put last keyboard press into A
		cp 112					; was "p" pressed?        **_in Emulator F4H F5h is been recognised instead of 112_**
		jr z, pright			; jump to PRIGHT
		cp 111				    ; was "o" pressed?               F4H	
		jr z, pleft				; jump to PLEFT
		cp 32					; was " " pressed?
		jr z, pfire				; jump to PFIRE
		cp 114					; was "r" pressed? Why in Emulator F7h ????
		jr z, newgame			; jump to NEWGAME
		jr ploop				; maintain player input loop

Tutorial with full listing of connect 4:
https://gist.github.com/darrylsloan/e2be3b95bc0cfc390f30ea833c858fc4

Can you have a look at it?

Regards,
Albert

p.s.
Really love your project!!

**Comment by Dotneteer** [comment]
Albert, I managed to reproduce the issue according to your instructions. I'm working on fixing it.

**Comment by Dotneteer** [comment]
I did manage to identify the issue. When you execute the "Run Z80 program" command, it starts the Spectrum virtual machine, waits while it reaches the the #12AC address (the entry point of the main execution cycle). Then, the IDE pauses the virtual machine, loads the code into the memory, and jumps to its entry address.
Unfortunately, this scenario leads to a strange -- but logical -- situation: the keyboard channel stays in "K" state, so pressing "O" (111) is represented as if you pressed "POKE" (code #F4), "P" (code) is observed as "PRINT" (code #F5), and so on.
When you start the emulator and LOAD the code, the keyboard channel is in "L" mode, and everything works as normal.
I plan to resolve this issue by modifying the "Run Z80 Program" command to put the keyboard into "L" mode before starting the custom code.

**Comment by Dotneteer** [comment]
I managed to resolve the issue as I explained in the comment above. In the future I will do some refactoring to allow a more generic way to prepare the virtual machine to run a custom code injected into the virtual machine.
