### ISSUE TITLE
Tutorial program in emulator not working

### ISSUE THREAD

**Issue by starquake** [Dotneteer/spectnetide#74]
I'm a C# developer that still loves his Speccy, so to find this blew my mind!

I was about to follow a tutorial but the result (at the bottom) does not work correctly in the emulator.
https://chuntey.wordpress.com/2010/01/12/tutorial-zx-spectrum-machine-code-game-30-minutes/

The keys don't work (bottom row of the speccy keyboard) and it crashes.

When I exported it to a TZX it worked fine in FUSE.

I use the normal ZX 48 PAL machine

**Comment by Dotneteer** [comment]
Starquake,
Thanks for reporting me this issue. I will check it as soon as possible. I'd be happy, if you'd share any more details.

**Comment by starquake** [comment]
Great! I'll see if I can look into it some more.

**Comment by Dotneteer** [comment]
Starquake,

I checked the issue you mentioned. The code did not crash. I carried out these steps:

1. Created a new ZX Spectrum 48K PAL project
2. Copied the final code into the `Code.z80asm` file
3. Started the machine, and wrote into this BASIC program:
```
10 PRINT AT 0,0;"Your score was";USR 33000
```
4. Paused the machine.
5. In Solution Explorer, I right-clicked `Code.z80asm`, and run the __Inject Z80 Code__ command.
6. In ZX Spectrum I issued RUN. (by pressing "R" and "Enter")
7. The code started working, _nonetheless the machine did not respond to keystrokes._

I checked the Z80 code, and found it was faulty (I do not know why it worked in FUSE). There was an issue in the code, as it tested the keyboard in a wrong way. Here is the correct code:

```
principalloop
	ld hl,(32900) ;retrieve car posn
	ld a,56  ;erase car
	ld (hl),a
	ei
	ld bc,65278;read keyboard caps to v
	in a,(c)
	cp 253 ; !!! In the wrong code it is 191
	jr nz, moveright
	inc l
moveright
	ld bc,32766 ;read keyboard space to b
	in a,(c)
	cp 253 ; !!! In the wrong code it is 191
	jr nz, dontmove
	dec l
dontmove
        ; ...
```
You can find more information about handling the ZX Spectrum keyboard in machine code in this document: https://computerarchive.org/files/comp/books/ZX%20spectrum/SpectrumMachineLanguageForTheAbsoluteBeginner.pdf 
Please check page 228 that shows the keyboard layout.

I'd be happy if you could make it clear what did crash in your case. Was it the the ZX Spectrum virtual machine window (in the IDE) or the ZX Spectrum code you ran?

Istvan

**Comment by starquake** [comment]
Wow that's amazing! 

That's weird. I pasted the code in Zeus and there it worked too. Maybe some weird edge case? 

I'll try it with your changes. Also thanks a lot for that PDF! That looks very helpful. Do you have any more tips? I'm off work for 3 weeks next week and planning to spend my time learning Z80 Assembly.

**Comment by Dotneteer** [comment]
Starquake,

As of today, the community says that the code I provided is the one that should work properly. We still do not have info why the code works in other emulators...

**Comment by Dotneteer** [comment]
starquake,

If it would not work, just zip the ZX Spectrum project and add the attachment into this issue. I still would like to check the crash. I'm happy to investigate any issue :-)

**Comment by Asnivor** [comment]
@Dotneteer 

I'm assuming the original code source was written on an emulator.

It's probably a safe bet that during an IN that the keyboard responds to, many emulators will mask away Bits 5-7 (as they are nothing to do with the current half-row) and set Bits 5 and 7 (as is necessary according to 48k reference at WOS [here](https://www.worldofspectrum.org/faq/reference/48kreference.htm)) before returning the final result to the CPU/Memory.

Whether or not that is accurate compared to the original machines or not (probably not) it looks like the best way of providing compatibility in an emulator without having to worry about different ULA types and their associated differences (especially with regard to some models Bit6 ways (the tape bit). 

It could also just be a certain interpretation of all the different documentation out there I suppose. Emulator chinese whispers..etc.

This is I think why cp 191 works in the code above on certain emulators (unless I am way off the mark).

```
B7	B6	B5	B4	B3	B2	B1	B0
1	0	1	1	1	1	1	1
```

B5-B7 will always return the same in these emulators, leaving B0-B5 to be compared for reset bits (key presses).

To know for sure, you would need to be able to test on a real spectrum (and mine died a death a long time ago).

**Comment by Asnivor** [comment]
@starquake I believe FUSE has an 'Issue 2 Keyboard' emulation option. Maybe enable that and see if your compiled tzx still works the same?

**Comment by starquake** [comment]
I'll check that. But reading the link gives me the impression you are on the right track. There's even a test for it in BASIC there.

**Comment by Asnivor** [comment]
Also, I am not sure 253 is the correct choice here anyway.

This translates as:

```
B7	B6	B5	B4	B3	B2	B1	B0
1	1	1	1	1	1	0	1
```

But the code is looking for any change in the entire half-row, not just the Z key pressed. 

When no keys on the half-row are pressed, B0-B4 are all set. cp 253 will detect that any other keys apart from Z are pressed and only detect a Z keypress when it is pressed with another key on the same half-row.

If my thinking is correct (and there is a chance that it is not) then a value of 255 should work in spectnetide.

**Comment by Asnivor** [comment]
@starquake Yup, I see the BASIC test there.

@Dotneteer The doc on WOS states the following when INing from the ULA port:

```
Bit 6 of IN-Port 0xfe is the EAR input bit. The value read from this port is not trivial, as can be seen from the following program:

      10 OUT 254,BIN 11101111
      20 PRINT IN 254
      30 OUT 254,BIN 11111111
      40 PRINT IN 254
      50 GOTO 10
For a correct test do not press any key while running, and have no EAR input.

If the output is 191,255,191,255 etc, you are on real Spectrum Issue 3.
If output is always 191 or always 255, change the value in line 10 to BIN 11100111.
If output is then 191,255,191,255 etc, then you are on Spectrum Issue 2.
If output is still always 191 or always 255 you are on Spectrum emulator.
```

So the actual value of Bit6 appears to be dependent on 1. The type of ULA and/or 2. The last value OUTed to 0xfe:

```
The ULA chip uses the same pin (28) for all of the MIC socket, EAR socket and the internal speaker, so bits 3 and 4 of an OUT to Port 0xfe will affect bit 6 as read by an IN from Port 0xfe. The difference between Issue 2 and 3 machines is:

Value output to bit: 4  3  |  Iss 2  Iss 3   Iss 2 V    Iss 3 V
                     1  1  |    1      1       3.79       3.70
                     1  0  |    1      1       3.66       3.56
                     0  1  |    1      0       0.73       0.66
                     0  0  |    0      0       0.39       0.34
Iss 2 is value of bit 6 read by IN 254 after the appropriate OUT from an Issue 2, and Iss 3 is same for an Issue 3. Iss 2 V and Iss 3 V are voltage levels on pin 28 of the ULA chip after the OUT, with no input signal on the EAR socket.

From the above, it is clear that the difference between Issue 2 and 3 is:

On an Issue 3, an OUT 254 with bit 4 reset will give a reset bit 6 from IN 254.
On an Issue 2, both bits 3 and 4 must be reset for the same effect to occur.
```

So, on a real speccy a keyboard half-row read with *NO* keys presssed should always return either 191 or 255.

So emulators over the years have either implemented various ULA issue emulation, or just masked out Bit6 when returning IN to port 0xfe. Any variation from 191 or 255 would indicate one of more keypresses on that half-row.

**Comment by Dotneteer** [comment]
@asvinor: A pressed key is represented in a 0 bit, and not 1. So value 253 ($BF) checks if  Z is pressed.

In real code, I would not use this type of test. The correct way were this: 

```
ld bc,65278;read keyboard caps to v
	in a,(c)
	and $02;
	jr nz, moveright
       ; Z is pressed
```

**Comment by Dotneteer** [comment]
@asvinor: Thanks for the info on ULA revisions :-)

**Comment by Asnivor** [comment]
@Dotneteer that is correct, but it looks like the original code is not checking for a single keypress, it is checking for *any* keypress on that halfrow. This is why 191 should work if Bit6 is reset.

**Comment by Asnivor** [comment]
@Dotneteer just thinking out loud:

 cp is a subtraction without affecting a.

when cp 191 is executed:

if (a == n) { Z flag set }
if (a != n) { Z flag reset }

so if a key in the half-row is pressed, a != n and Z is reset.

then:

jr nz, moveright = jump to moveright is Z is reset

So we go to moveright if any key on the half-row is pressed

If you do cp 253 and the Z key is pressed (and nothing else pressed), a == n and the Z flag is *set*. Therefore the jr nz does not jump to moveright.

Unless I am missing something?

**Comment by Dotneteer** [comment]
@Asnivor, thanks for investing your time in solving this issue. According to the info you've sent me, I can clearly see that my SpectNetIde implementation does not handle Issue 2/3 with keyboard. 

I opened a bug (#75) to resolve this problem :-).

@starquake, thanks a lot!

**Comment by Asnivor** [comment]
@Dotneteer no problem :)
