### ISSUE TITLE
Exception on latest VS2017

### ISSUE THREAD

**Issue by gusmanb** [Dotneteer/spectnetide#76]
When I have the complement installed, each time I open VS it complains about cannot load SpectNetIde. This is all the info I could get:

SetSite failed for package [SpectNetPackage]Source: &apos;mscorlib&apos; Description: No se pueden cargar uno o varios tipos requeridos. Recupere la propiedad LoaderExceptions para obtener m&#x00E1;s informaci&#x00F3;n.&#x000D;&#x000A;System.Reflection.ReflectionTypeLoadException: No se pueden cargar uno o varios tipos requeridos. Recupere la propiedad LoaderExceptions para obtener m&#x00E1;s informaci&#x00F3;n.&#x000D;&#x000A;   en System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)&#x000D;&#x000A;   en System.Reflection.RuntimeModule.GetTypes()&#x000D;&#x000A;   en System.Reflection.Assembly.GetTypes()&#x000D;&#x000A;   en Spect.Net.VsPackage.Vsx.VsxPackage.ScanTypes(Func`2 condition, Action`1 action) en C:\Users\dotne\Source\Repos\spectnetide\VsIntegration\Spect.Net.VsPackage\Vsx\VsxPackage.cs:l&#x00ED;nea 197&#x000D;&#x000A;   en Spect.Net.VsPackage.Vsx.VsxPackage.&lt;InitializeAsync&gt;d__13.MoveNext() en C:\Users\dotne\Source\Repos\spectnetide\VsIntegration\Spect.Net.VsPackage\Vsx\VsxPackage.cs:l&#x00ED;nea 87&#x000D;&#x000A;--- Fin del seguimiento de la pila de la ubicaci&#x00F3;n anterior donde se produjo la excepci&#x00F3;n ---&#x000D;&#x000A;   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   en Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass17_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- Fin del seguimiento de la pila de la ubicaci&#x00F3;n anterior donde se produjo la excepci&#x00F3;n ---&#x000D;&#x000A;   en Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   en Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;   en Microsoft.VisualStudio.Services.VsTask.GetResult()</description>
    <guid>{1B214806-BC31-49BD-BE5D-79AC4A189F3C}

**Comment by Dotneteer** [comment]
Thanks, @gusmanb. Do you have an opportunity to check that this issue exists on English VS 2017? Fortunately, your error report gives me some hint. I have not managed to reproduce the issue on an English VS 2017 yet, nonetheless, I try...

**Comment by gusmanb** [comment]
Hi. Sorry for the delay, I've been very busy this week. I can't install a new version of VS on this machine right now as it's my development one. But, next week I will receive a new HDD and I can try to install a completely clean Windows, a new VS, in english and spanish, and check if I can reproduce the problems on these.

If you need any other test under my current VS I will be very glad to perform it.

Cheers.

**Comment by Dotneteer** [comment]
Great 😊. Let me know, what you find! I suspect, the issue might be correlated to Spanish VS 2017, or something else on your machine. Nonetheless, it might be a bug is SpectNetIde, too. I definitely keep this issue open.

**Comment by Dotneteer** [comment]
@gusmanb, it seems that there is some issue with .NET/Windows and the Spanish language. See #77, which reports the same issue on Check Windows...

**Comment by Dotneteer** [comment]
@gusmanb, I have a few more questions to you to investigate the issue:
* What operating system do you use (OS and language versions, please)
* Did you install SpectNetIde from the Visual Studio Marketplace, or compiled the source code obtained from Git?

**Comment by Dotneteer** [comment]
Issue fixed in release 1.10.3
