### ISSUE TITLE
Watch memory (using symbols?)

### ISSUE THREAD

**Issue by p3365** [Dotneteer/spectnetide#91]
When I debug my program, I like to look at the contents of memory to see exactly what is stored.

For example, I may have a memory location declared within my program that has a label:

`LD DE,(PRINT_LOC)`

Somewhere else in the program this is declared:

`PRINT_LOC: DEFW 0`

The actual memory location of the above label is generated at compile time. I wish to look at the content of this address. I can use the ZX Spectrum Memory window. I can type "G PRINT_LOC" to scroll to the address. However its not clear which memory address is the right one to look at. It appears to be on the _second_ line of the memory window (not the first). And if the actual address is not aligned to 8 bytes, it could be anywhere on that line but its not obvious.

It would be nice to have a "Watch" window where I could watch any memory location. This could also use symbol definitions to allow me to watch It would be nice to be able to watch as an 8 bit value, 16 bit value or raw memory.

**Comment by Dotneteer** [comment]
Useful idea. I need time to design and implement this feature...

**Comment by Dotneteer** [comment]
Released in v1.14.0
