### ISSUE TITLE
[feature request]  auto-jump to memory location on program start

### ISSUE THREAD

**Issue by nww02** [Dotneteer/spectnetide#95]
Whenever you stop/start the code, the memory window resets back to 0000 or 3DF0.   

Therefore, I have to keep highlighting the window, doing g 8000 (or similar) to locate my memory, every time I run the program.   

I'm probably missing it, but if the feature isn't there, could you please add something that auto-jumps the memory window (on execution) to:
a) the first byte of the code,  or;
b) wherever the last g command sent it before the reboot or;
c) whatever works for you, like a #pragma ...

If coupled with Request 93, that would mean just pressing F5 would really streamline development nicely :)

**Comment by Dotneteer** [comment]
I'm happy to implement such a feature. What about this solution:
* If there's an `ENT` pragma in the code (entry point), the Z80 Disassembly window opens this location.
* Else, if there's an `XENT` pragma in the code (exported code entry point), the Z80 Disassembly window opens this location.
* Otherwise, the Z80 Disassembly window opens the start location (ORG) of the code.

You can use this behavior when you invoke the Run Z80 Code command.

**Comment by nww02** [comment]
As I often place my used variables at the .org point, yep, that works perfectly for me.    I'll have to research the .xent pragma to see if that can be used by anyone else who would want to focus on their variables.     

For the most part, you want to use the memory screen to see where your first defb is at more often than where your code is, I think.  

Although, I see others asking for a watch window, which would be a good alternative.

Thanks!

**Comment by Dotneteer** [comment]
Thanks for the addition! I will implement the Watch window, but it will take time. Your suggestion is a "cheaper" feature.

**Comment by Dotneteer** [comment]
Feature implemented, will be released soon. Works with the ZX Spectrum Memory and Z80 Disassembly tool windows.

**Comment by nww02** [comment]
Awesome!! Thanks :)       Your work is helping me realise a dream I've had for 35 years... Thank you so much!

**Comment by Dotneteer** [comment]
Fixed, released in v1.13.1.

**Comment by nww02** [comment]
It works perfectly, thank you! :)
