### ISSUE TITLE
[feature request]  Highlight where PC,SP,IX, IY, HL are addressing in memory map window

### ISSUE THREAD

**Issue by nww02** [Dotneteer/spectnetide#99]
When I'm debugging, I often have one or more of the 16-bit registers pointing at chunks of memory.    Especially when I'm blitting bytes to/from screen RAM.   

It's relatively easy to look at 80B0 then count 5 over to 80B5  (or whatever), but it does add time...

It would be nice if, after the running code changes their value, the 16-bit regs could be colour coded and the byte in memory which is at their value can be highlighted with their colour.   If they're not being used for memory addressing, then yeah, they'll flash some random bytes on and off, but the developer will know what they're looking for (e.g. IX might be red, so look for the red highlight scanning through the sprite sheet mem bytes).

It's just a nice-to-have to make debugging simpler, and prevent all those oily smears on the screen from my finger tracing the pointers :)

**Comment by Dotneteer** [comment]
It would be a very useful feature. With the current architecture of the ZX Spectrum Memory window it requires a thorough refactoring, but it's not impossible :-).
I also plan to display memory addresses as you move the mouse over memory bytes.

**Comment by Dotneteer** [comment]
Implemented :-). 

Now, the memory view highlights the addresses pointed by BC, DE, HL, IX, IY, PC, and SP.

![image](https://user-images.githubusercontent.com/4783390/51585806-19bd0580-1edb-11e9-81f1-39a79fe48eec.png)

As you move over a memory contents value, the view displays a few data in a tooltip, including the memory address and registers pointing to that very memory address.

In the __Tools|Options__ dialog, you can set colors for each register pair highlight:

![image](https://user-images.githubusercontent.com/4783390/51552041-0de82980-1e70-11e9-8298-8f27e3437d1f.png)

You can use RGB colors in #_rrggbb_ format, where _rr_, _gg_, and _bb_ are two hexadecimal digits; or you can use one of these predefined color names:

![image](https://user-images.githubusercontent.com/4783390/51552216-64edfe80-1e70-11e9-8088-78478b733fa2.png)

**Comment by Dotneteer** [comment]
Released in v1.14.0
